CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    tier VARCHAR(20) NOT NULL DEFAULT 'FREE',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    display_name VARCHAR(100) NOT NULL,
    real_name VARCHAR(100),
    last_login_at TIMESTAMPTZ,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email)
);

INSERT INTO users(id, email, password_hash, role, tier, status, display_name, real_name, last_login_at, is_deleted, created_at, updated_at)
VALUES
    (1, 'skill-pg-student@example.com', '$2a$10$seed', 'STUDENT', 'FREE', 'ACTIVE', 'PG Skill Student', 'PG Skill Student', NULL, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'skill-pg-admin@example.com', '$2a$10$seed', 'ADMIN', 'FREE', 'ACTIVE', 'PG Skill Admin', 'PG Skill Admin', NULL, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
