CREATE TABLE skills (
    node_code VARCHAR(100) PRIMARY KEY,
    label VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    parent_code VARCHAR(100),
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_skills_parent_code FOREIGN KEY (parent_code) REFERENCES skills(node_code)
);

CREATE TABLE skill_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_user_id BIGINT NOT NULL,
    node_code VARCHAR(100) NOT NULL,
    progress_status VARCHAR(20) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_skill_progress_user_node UNIQUE (student_user_id, node_code),
    CONSTRAINT fk_skill_progress_user FOREIGN KEY (student_user_id) REFERENCES users(id),
    CONSTRAINT fk_skill_progress_node FOREIGN KEY (node_code) REFERENCES skills(node_code)
);

CREATE TABLE skill_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_node_code VARCHAR(100) NOT NULL,
    target_node_code VARCHAR(100) NOT NULL,
    relation_type VARCHAR(30) NOT NULL,
    label VARCHAR(100) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_skill_relations_unique UNIQUE (source_node_code, target_node_code, relation_type),
    CONSTRAINT fk_skill_relations_source FOREIGN KEY (source_node_code) REFERENCES skills(node_code),
    CONSTRAINT fk_skill_relations_target FOREIGN KEY (target_node_code) REFERENCES skills(node_code)
);

CREATE TABLE skill_node_resources (
    resource_code VARCHAR(100) PRIMARY KEY,
    node_code VARCHAR(100) NOT NULL,
    resource_type VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    source_label VARCHAR(100) NOT NULL,
    duration_label VARCHAR(50) NOT NULL,
    link_url VARCHAR(500) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_skill_node_resources_code UNIQUE (resource_code),
    CONSTRAINT fk_skill_node_resources_node FOREIGN KEY (node_code) REFERENCES skills(node_code)
);
