CREATE TABLE mentor_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    approval_status VARCHAR(20) NOT NULL DEFAULT 'APPROVED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_mentor_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_mentor_profiles_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE enterprise_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    approval_status VARCHAR(20) NOT NULL DEFAULT 'APPROVED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_enterprise_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_enterprise_profiles_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE student_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    job_status VARCHAR(50),
    school_name VARCHAR(150),
    school_name_key VARCHAR(160),
    major VARCHAR(100),
    grade VARCHAR(20),
    gpa VARCHAR(50),
    target_position VARCHAR(100),
    honors TEXT,
    github VARCHAR(255),
    portfolio VARCHAR(255),
    social_links_json TEXT,
    phone VARCHAR(50),
    wechat VARCHAR(100),
    avatar_bucket VARCHAR(100),
    avatar_object_key VARCHAR(255),
    avatar_content_type VARCHAR(100),
    avatar_updated_at TIMESTAMPTZ,
    skill_tags VARCHAR(512),
    self_intro TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_student_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_student_profiles_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_student_profiles_school_name_key ON student_profiles(school_name_key);

CREATE TABLE student_profile_privacy_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_user_id BIGINT NOT NULL,
    settings_json TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_student_profile_privacy_settings_user UNIQUE (student_user_id),
    CONSTRAINT fk_student_profile_privacy_settings_user FOREIGN KEY (student_user_id) REFERENCES users(id)
);

CREATE TABLE student_portrait_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_user_id BIGINT NOT NULL,
    portrait_tags TEXT NOT NULL,
    evidence TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_student_portrait_snapshots_user UNIQUE (student_user_id),
    CONSTRAINT fk_student_portrait_snapshots_user FOREIGN KEY (student_user_id) REFERENCES users(id)
);
