CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    moderation_status VARCHAR(20) NOT NULL DEFAULT 'PASS',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    moderation_status VARCHAR(20) NOT NULL DEFAULT 'PASS',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts(id),
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE post_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_post_likes_unique UNIQUE (post_id, user_id),
    CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES posts(id),
    CONSTRAINT fk_post_likes_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE ai_call_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    task_type VARCHAR(30) NOT NULL,
    scene_code VARCHAR(60),
    provider VARCHAR(50) NOT NULL,
    model VARCHAR(100) NOT NULL,
    route_code VARCHAR(80),
    route_policy_code VARCHAR(80),
    latency_ms BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    error_code VARCHAR(20),
    request_tokens INT NOT NULL DEFAULT 0,
    response_tokens INT NOT NULL DEFAULT 0,
    total_tokens INT NOT NULL DEFAULT 0,
    thoughts_tokens INT NOT NULL DEFAULT 0,
    reasoning_effort VARCHAR(20),
    thinking_budget INT,
    thinking_level VARCHAR(40),
    estimated_cost NUMERIC(10, 6) NOT NULL DEFAULT 0,
    charged_points INT NOT NULL DEFAULT 0,
    quota_weight INT NOT NULL DEFAULT 1,
    result_summary TEXT,
    result_payload_json TEXT,
    user_deleted_at TIMESTAMPTZ,
    user_tier VARCHAR(20) NOT NULL DEFAULT 'FREE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_call_logs_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_ai_call_logs_user_task_time ON ai_call_logs(user_id, task_type, created_at);

CREATE TABLE interview_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    student_user_id BIGINT NOT NULL,
    target_role VARCHAR(100) NOT NULL,
    mode VARCHAR(30) NOT NULL,
    resume_context_json TEXT,
    session_context_json TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    reply_round_limit INT NOT NULL DEFAULT 8,
    reply_round_used INT NOT NULL DEFAULT 0,
    summary_generated INT NOT NULL DEFAULT 0,
    prepaid_points INT NOT NULL DEFAULT 0,
    reserved_quota_weight INT NOT NULL DEFAULT 5,
    summary_overall_score INT,
    summary_strengths_json TEXT,
    summary_weaknesses_json TEXT,
    summary_suggestions_json TEXT,
    summary_provider VARCHAR(50),
    summary_model VARCHAR(100),
    summary_latency_ms BIGINT,
    summary_generated_at TIMESTAMPTZ,
    finish_reason VARCHAR(50),
    ended_by_ai INT NOT NULL DEFAULT 0,
    user_deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_interview_sessions_session_id UNIQUE (session_id),
    CONSTRAINT fk_interview_sessions_user FOREIGN KEY (student_user_id) REFERENCES users(id)
);

CREATE INDEX idx_interview_sessions_user_time ON interview_sessions(student_user_id, created_at);

CREATE TABLE interview_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_pk BIGINT NOT NULL,
    sender_role VARCHAR(20) NOT NULL,
    message_text TEXT NOT NULL,
    coach_feedback TEXT,
    score_hint INT,
    audio_object_key VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_interview_messages_session FOREIGN KEY (session_pk) REFERENCES interview_sessions(id)
);

CREATE INDEX idx_interview_messages_session_time ON interview_messages(session_pk, created_at);
