-- 从 schema.sql 终态导出的 PostgreSQL 技能树静态快照。
-- 当前只做 upsert，不主动删除旧 PG pilot 中已存在的静态 seed，
-- 以避免在已有实验数据时误伤 skill_progress 等依赖链。

INSERT INTO skills(node_code, label, description, parent_code, sort_order, created_at, updated_at) VALUES
    ('programming_language_foundations', '计算机科学成长底座', '作为整张技能星图的中央枢纽，把技术基础、工程实践、职业发展和成长韧性汇成一棵主树。', NULL, 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('computational_thinking', '计算思维与问题拆解', '把底层语言、数据结构与算法训练串成一条抽象问题与拆解问题的主线。', 'programming_language_foundations', 200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('c_programming_basics', 'C 语言与底层感知', '从指针、内存和过程式编程建立对机器执行过程的直觉。', 'computational_thinking', 210, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('memory_model_pointers', '内存模型与指针意识', '理解地址、内存布局、生命周期和指针操作，为系统编程打地基。', 'c_programming_basics', 211, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('data_structures', '数据结构与组织方式', '围绕线性表、树、图、哈希和状态表示组织问题信息。', 'computational_thinking', 220, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('algorithms_analysis', '算法分析与复杂度意识', '通过时间复杂度、空间复杂度和常见策略训练解题与实现判断力。', 'data_structures', 221, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('graph_problem_modeling', '图与关系建模', '把复杂业务、网络和依赖关系抽象成图结构与状态迁移问题。', 'algorithms_analysis', 222, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('problem_solving_patterns', '问题求解套路', '沉淀搜索、回溯、贪心、分治与动态规划的识别信号。', 'algorithms_analysis', 223, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('java_programming', 'Java 语言与工程实践', '掌握面向对象语法、标准库和工程开发里最常见的 Java 基础能力。', 'programming_language_foundations', 300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('object_oriented_modeling', '对象建模与职责拆分', '把类、接口、对象协作与职责边界设计得更稳定、更清晰。', 'java_programming', 310, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('design_patterns_refactoring', '设计模式与重构', '通过模式识别和重构手法提升面向对象代码的扩展性与可维护性。', 'object_oriented_modeling', 311, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('engineering_code_conventions', '工程编码规范', '围绕命名、分层、异常、日志与可读性形成稳定编码习惯。', 'object_oriented_modeling', 312, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('java_collections_io', '集合、I/O 与并发入口', '从集合框架、文件 I/O 到线程基础，建立 Java 工程运行时认知。', 'java_programming', 320, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('concurrent_programming_basics', '并发编程基础', '理解线程安全、锁、线程池与并发容器的基本用法与风险。', 'java_collections_io', 321, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('software_engineering_delivery', '软件工程与应用交付', '把需求理解、系统设计、协作开发、测试和交付串成完整工程闭环。', 'programming_language_foundations', 400, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('requirement_analysis', '需求分析与任务拆解', '在动手实现前先把问题背景、目标、边界与验收标准讲清楚。', 'software_engineering_delivery', 410, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('software_architecture_design', '系统设计与架构分层', '从模块职责、边界划分到调用链路，搭起应用系统的主骨架。', 'requirement_analysis', 411, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('backend_service_development', '后端服务开发', '把接口、服务层、持久层与业务规则组织成稳定可维护的后端系统。', 'software_architecture_design', 412, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('service_layer_design', '服务层设计', '明确应用服务、领域对象、事务边界与对外暴露接口的组织方式。', 'backend_service_development', 413, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('api_contract_design', '接口契约设计', '围绕资源、协议、错误码、版本演进和协作边界设计稳定 API。', 'service_layer_design', 414, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('domain_modeling_design', '业务领域建模', '把真实业务概念映射成可演进的数据对象、状态机和规则边界。', 'service_layer_design', 415, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('frontend_engineering', '前端工程', '关注浏览器、组件化、状态管理与面向产品界面的前端实现方式。', 'software_architecture_design', 420, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('browser_runtime_mechanics', '浏览器运行机制', '理解渲染流水线、事件循环、缓存与网络请求在浏览器中的协作。', 'frontend_engineering', 421, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('frontend_component_architecture', '组件架构设计', '通过组件边界、复用策略和职责拆分构建可维护的前端界面。', 'frontend_engineering', 422, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('state_data_flow', '状态与数据流', '梳理页面状态、异步数据和组件通信的来源、去向与同步策略。', 'frontend_component_architecture', 423, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('collaborative_development', '协作开发流程', '通过任务拆分、代码评审、分支策略和文档同步提升多人协作效率。', 'software_engineering_delivery', 430, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('automated_testing', '自动化测试', '用测试守住关键业务路径、模块协作和版本回归稳定性。', 'collaborative_development', 431, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('unit_integration_testing', '单元与集成测试', '让测试覆盖函数、模块和依赖协作，而不是只停留在 Happy Path。', 'automated_testing', 432, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('end_to_end_regression', '端到端回归验证', '围绕关键业务路径设计回归用例，守住版本发布前的稳定性。', 'automated_testing', 433, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('devops_delivery', 'DevOps 与发布交付', '围绕构建、部署、环境管理与发布回滚形成交付工程能力。', 'collaborative_development', 440, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ci_cd_pipeline', 'CI/CD 流水线', '把构建、检测、部署与回滚路径收进自动化流水线。', 'devops_delivery', 441, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('observability_incident_response', '可观测性与故障响应', '通过日志、指标、链路与值班流程定位线上异常并快速恢复。', 'devops_delivery', 442, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('data_database_systems', '数据、数据库与信息系统', '从数据建模、数据库到数仓分析与数据系统理解信息如何被沉淀和使用。', 'programming_language_foundations', 500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('relational_databases', '关系数据库', '掌握表结构、约束、SQL、索引与关系型数据组织方式。', 'data_database_systems', 510, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('sql_query_writing', 'SQL 编写与结果验证', '把查询语句写对、写清楚，并能验证结果、边界和代价。', 'relational_databases', 511, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('data_modeling', '数据建模', '把业务对象、关系和查询需求沉淀成兼顾一致性与演进性的结构。', 'relational_databases', 512, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('transaction_consistency', '事务与一致性', '掌握隔离级别、锁、并发写入和一致性约束的核心问题。', 'data_modeling', 513, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('query_optimization', '查询优化', '理解执行计划、索引命中、慢查询定位和常见 SQL 调优策略。', 'data_modeling', 514, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('data_warehouse_etl', '数据仓库与 ETL', '理解离线数仓、指标口径、批处理链路和基础 ETL 流程。', 'data_database_systems', 520, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('big_data_foundations', '大数据基础', '理解批处理、流处理、消息系统和规模化数据处理的基本框架。', 'data_warehouse_etl', 521, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('analytics_data_visualization', '分析表达与数据可视化', '把分析结果整理成图表、指标故事和可沟通的结论。', 'data_warehouse_etl', 522, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('systems_infrastructure', '系统与基础设施', '从组成原理、操作系统、分布式与云原生基础设施构建系统视角。', 'programming_language_foundations', 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('computer_organization', '计算机组成原理', '理解 CPU、存储层次、指令执行与整机结构，补齐底层运行直觉。', 'systems_infrastructure', 610, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('operating_systems', '操作系统', '从进程线程、内存管理到文件与调度理解系统资源如何被组织。', 'computer_organization', 612, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('process_thread_models', '进程与线程模型', '拆清进程、线程、上下文切换和调度之间的关系。', 'operating_systems', 613, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('memory_management', '内存管理', '理解虚拟内存、分页、分段、缓存与内存泄漏定位思路。', 'operating_systems', 614, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('file_system_io', '文件系统与 I/O', '理解文件抽象、磁盘读写、缓存与常见 I/O 模型。', 'operating_systems', 615, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('linux_operations', 'Linux 运维基础', '围绕命令行、权限、日志、进程和服务管理建立系统排障能力。', 'operating_systems', 616, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('shell_tooling_automation', 'Shell 与自动化工具', '把命令行、脚本和批处理能力沉淀成日常排障与自动化效率。', 'linux_operations', 617, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hardware_embedded', '硬件与嵌入式', '理解数字逻辑、单片机、嵌入式软件与设备联动的工程链路。', 'computer_organization', 620, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('digital_logic', '数字逻辑', '围绕布尔代数、组合逻辑和时序逻辑建立硬件表达基础。', 'hardware_embedded', 621, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('microcomputer_principles', '微机原理', '理解总线、中断、寄存器和外设通信在嵌入式场景里的工作方式。', 'hardware_embedded', 622, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('embedded_systems', '嵌入式系统', '面向资源受限设备学习驱动、调试与软硬件协同实现。', 'microcomputer_principles', 623, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('iot_system_design', '物联网系统设计', '连接传感器、边缘设备、通信链路和云端平台，形成完整 IoT 方案。', 'embedded_systems', 624, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('network_security', '网络与安全', '聚焦网络通信、协议分层与安全防护，建立面向真实互联网系统的基础认知。', 'systems_infrastructure', 630, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('computer_networks', '计算机网络', '掌握网络分层、设备角色、请求路径和典型排障思路。', 'network_security', 631, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('network_protocols', '网络协议', '理解 TCP/IP、HTTP、DNS、TLS 等协议在真实业务中的协作方式。', 'computer_networks', 632, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('web_security', 'Web 安全基础', '识别认证授权、XSS、CSRF、注入和常见安全设计缺口。', 'network_protocols', 633, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('applied_cryptography', '应用密码学', '理解哈希、加密、签名、证书与密钥管理在工程中的用法。', 'web_security', 634, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('secure_engineering', '安全工程实践', '把安全要求落实到接口、配置、代码审计和上线检查清单。', 'applied_cryptography', 635, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('distributed_systems', '分布式系统基础', '理解复制、负载均衡、服务发现和跨节点调用中的关键难题。', 'network_security', 640, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('service_governance_resilience', '服务治理与韧性设计', '围绕超时、限流、熔断、重试与降级处理复杂调用链。', 'distributed_systems', 641, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('cloud_native_basics', '云原生基础', '围绕容器、镜像、编排和配置管理理解现代基础设施的运行方式。', 'distributed_systems', 642, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('container_kubernetes', '容器编排与 Kubernetes', '从镜像、Pod、Service 到部署策略理解云原生运行时。', 'cloud_native_basics', 643, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_data_science', '智能与数据科学', '从数据处理、统计推断到机器学习与大模型应用构建智能系统视角。', 'programming_language_foundations', 700, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('python_data_tools', 'Python 数据工具', '用 Python 处理数据、写脚本和搭实验原型，形成数据工作台能力。', 'ai_data_science', 710, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('data_cleaning_feature_engineering', '数据清洗与特征工程', '把原始数据整理成可训练、可评估、可复用的特征输入。', 'python_data_tools', 711, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('statistics_foundation', '统计学基础', '从概率、分布到估计与推断，为机器学习与实验分析做准备。', 'ai_data_science', 720, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('probability_inference', '概率与统计推断', '从分布、期望到估计与假设检验，补齐机器学习前置数学。', 'statistics_foundation', 721, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('machine_learning', '机器学习', '围绕特征、训练、评估和泛化能力理解典型机器学习流程。', 'statistics_foundation', 722, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('model_evaluation_validation', '模型评估与验证', '围绕指标选择、数据切分、过拟合与泛化能力建立评估框架。', 'machine_learning', 723, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tree_linear_models', '线性模型与树模型', '掌握最常见的传统机器学习模型及其适用边界。', 'machine_learning', 724, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('deep_learning', '深度学习', '通过神经网络、反向传播和训练策略理解表示学习方法。', 'machine_learning', 725, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('neural_network_training', '神经网络训练流程', '围绕损失函数、优化器、正则化和调参形成训练闭环。', 'deep_learning', 726, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('llm_applications', '大模型应用', '把提示词工程、知识检索与工具调用组织成可落地 AI 应用。', 'deep_learning', 727, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prompt_rag_agent', 'Prompt、RAG 与 Agent 设计', '把提示词工程、检索增强和工具调用组织成可落地的大模型方案。', 'llm_applications', 728, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('recommendation_systems', '推荐系统基础', '把召回、排序、特征与反馈闭环组合成个性化推荐系统。', 'machine_learning', 729, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_programming_engineering', 'AI 编程与智能开发', '把提示词、AI 协作编码、编码 Agent 与工程治理按真实落地流程串成一棵应用型学习主树。', 'programming_language_foundations', 750, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prompt_context_engineering', '提示词与上下文工程', '先学会把目标、约束、仓库片段与运行信息组织成模型真正能用的输入。', 'ai_programming_engineering', 751, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prompt_pattern_design', '提示模式设计', '围绕角色设定、few-shot、输出模板和分步指令沉淀稳定可复用的提示套路。', 'prompt_context_engineering', 752, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('context_window_orchestration', '上下文窗口编排', '学会裁剪文件、日志、文档和历史对话，让模型在有限窗口里看到最关键的信息。', 'prompt_context_engineering', 753, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tool_schema_design', '工具接口与 Schema 设计', '在理解上下文裁剪之后，继续学习把工具参数、结构化返回和调用约束设计得足够清晰。', 'context_window_orchestration', 754, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_native_development', 'AI 原生开发流程', '把需求拆解、原型试错、AI 协作编码与人工验收组织成新的开发工作流。', 'ai_programming_engineering', 760, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('vibe_coding_workflows', 'Vibe Coding 原型流', '适合快速探索交互、原型和想法，但必须辅以人工审查、测试和版本管理。', 'ai_native_development', 761, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_pair_programming', 'AI 结对编程', '把补全、解释、实现、纠错与人工修改串成高频协作循环，逐步形成稳定的协作节奏。', 'ai_native_development', 762, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_debug_refactor_loops', 'AI 调试与重构闭环', '在结对编程之后继续深入，让模型参与定位问题、验证修改和辅助重构，但仍由人工最终验收。', 'ai_pair_programming', 763, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_coding_agent_systems', '编码 Agent 系统', '从上下文检索、工具链调用到多阶段执行，理解编码 Agent 的系统组成。', 'ai_programming_engineering', 770, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_codebase_grounding', '代码库检索与上下文对齐', '先让模型在真实仓库结构、接口契约、依赖边界和既有风格中找到正确上下文。', 'ai_coding_agent_systems', 771, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_coding_agent_tools', '工具调用与编码 Agent', '在代码库对齐之后，再把搜索、读写文件、运行测试与命令执行串成可控的编码代理链路。', 'ai_codebase_grounding', 772, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('multi_agent_workflows', '多 Agent 协作编排', '当单 Agent 链路稳定之后，再把需求分析、实现、测试和审查组织成多阶段代理流水线。', 'ai_coding_agent_tools', 773, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_engineering_governance', 'AI 工程治理', '围绕评测、审查、路由、成本和安全边界，让 AI 编程能力真正能落地到团队流程。', 'ai_programming_engineering', 780, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_code_review_guardrails', 'AI 代码审查与护栏', '先围绕 diff 审查、测试门禁、权限边界和回滚策略建立 AI 输出的基础护栏。', 'ai_engineering_governance', 781, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_eval_observability', 'AI 编程评测与可观测性', '在护栏建立后，进一步通过任务集、通过率、失败留痕和运行指标判断链路是否真正有效。', 'ai_code_review_guardrails', 782, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('model_routing_cost_control', '模型路由与成本控制', '最后再根据任务类型、时延要求、预算和稳定性选择模型、降级路径与缓存策略。', 'ai_eval_observability', 783, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('theory_history', '计算理论与技术史', '把理论基础、编译原理、技术演进和工程伦理放进同一条长期学习主线。', 'programming_language_foundations', 800, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('discrete_mathematics', '离散数学', '从集合、逻辑、关系到图论建立形式化表达能力。', 'theory_history', 810, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('logic_and_proofs', '逻辑与证明方法', '用命题逻辑、归纳法和反证法训练严谨推导能力。', 'discrete_mathematics', 811, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('compiler_principles', '编译原理', '理解词法、语法、中间表示和编译器把语言变成机器执行单元的过程。', 'discrete_mathematics', 812, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('cs_history', '计算机发展史', '理解关键技术浪潮、平台变迁与工程范式如何一轮轮演进。', 'theory_history', 820, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('open_source_culture', '开源协作文化', '从许可证、社区协作到公共技术生态理解开源世界的工作方式。', 'cs_history', 821, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('engineering_ethics', '工程伦理', '在隐私、偏见、平台责任与技术边界之间形成更稳的判断框架。', 'open_source_culture', 822, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('technology_society_governance', '技术治理与社会影响', '从平台责任、算法治理到公共影响理解技术决策的外部后果。', 'engineering_ethics', 823, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('career_employment_readiness', '职业发展与求职准备', '围绕岗位理解、简历表达与求职策略，建立从校园到就业市场的过渡能力。', 'programming_language_foundations', 900, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('career_positioning', '职业定位', '理解自己的能力边界、兴趣方向和阶段性求职目标。', 'career_employment_readiness', 910, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('job_market_research', '岗位信息研判', '学会拆解 JD、岗位能力图谱与行业差异，判断自己该补什么。', 'career_positioning', 911, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('networking_personal_brand', '人脉拓展与个人品牌', '通过校友、社区、公开表达和持续输出建立长期职业影响力。', 'job_market_research', 912, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('resume_portfolio', '简历与作品集表达', '把经历、项目和成果组织成 HR 与面试官能迅速抓住重点的材料。', 'career_positioning', 920, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('project_storytelling', '项目叙事与成果表达', '把项目背景、决策过程、指标结果和个人贡献讲成完整故事。', 'resume_portfolio', 921, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('interview_preparation', '面试准备与复盘', '围绕自我介绍、项目讲述、行为面试和复盘机制持续迭代表达。', 'resume_portfolio', 922, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('internship_workplace_adaptation', '实习与职场适应', '帮助学生在进入团队后快速适应任务节奏、协作方式与基本职业规范。', 'career_employment_readiness', 930, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('internship_goal_setting', '实习目标设定', '进入团队前明确阶段目标、学习重点和希望拿到的成果。', 'internship_workplace_adaptation', 931, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('task_execution_followup', '任务执行与跟进', '学会拆任务、报风险、同步进度并持续把事情推进到可交付。', 'internship_goal_setting', 932, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('workplace_communication', '职场沟通', '在向导师、同事或产品同步信息时保持准确、简洁和对齐。', 'internship_workplace_adaptation', 933, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('teamwork_collaboration', '团队协作', '在多人协作中理解上下游、反馈闭环与角色边界。', 'workplace_communication', 934, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('workplace_professionalism', '职场专业度', '在时间观念、文档沉淀、责任感和反馈习惯上形成稳定职业素养。', 'task_execution_followup', 935, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('wellbeing_self_management', '心理调节与成长韧性', '帮助学生在求职、学习和实习压力下保持稳定节奏与恢复能力。', 'career_employment_readiness', 940, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('stress_management', '压力管理', '识别压力来源，建立拆解任务、缓冲节奏和恢复状态的方法。', 'wellbeing_self_management', 941, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('emotion_regulation', '情绪调节', '识别情绪波动、避免陷入自我否定，并做更平稳的表达与恢复。', 'stress_management', 942, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('burnout_prevention', '倦怠预防', '识别长期高压和低反馈带来的倦怠信号，及时调整节奏与目标。', 'emotion_regulation', 943, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('growth_mindset', '成长型心态', '把失败、反馈与短期挫折转化成下一轮学习与行动计划。', 'wellbeing_self_management', 944, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('habit_energy_management', '习惯与精力管理', '通过作息、复盘、专注与阶段节奏管理维持长期输出。', 'growth_mindset', 945, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('self_reflection_planning', '自我复盘与阶段规划', '把学习、求职、实习过程中的反馈沉淀成下一阶段的行动计划。', 'growth_mindset', 946, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (node_code) DO UPDATE SET
    label = EXCLUDED.label,
    description = EXCLUDED.description,
    parent_code = EXCLUDED.parent_code,
    sort_order = EXCLUDED.sort_order,
    updated_at = EXCLUDED.updated_at;

INSERT INTO skill_relations(source_node_code, target_node_code, relation_type, label, sort_order, created_at, updated_at) VALUES
    ('computational_thinking', 'data_modeling', 'ADVANCE_TO', '抽象与拆解能力会迁移到数据建模', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('algorithms_analysis', 'machine_learning', 'ADVANCE_TO', '算法基础会直接支撑机器学习理解', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('object_oriented_modeling', 'domain_modeling_design', 'BRIDGE', '对象建模会过渡到业务领域建模', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('java_collections_io', 'distributed_systems', 'ADVANCE_TO', '并发与 I/O 基础会延伸到分布式调用', 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('frontend_component_architecture', 'api_contract_design', 'CO_LEARN', '前后端协作时适合同步补接口契约', 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('state_data_flow', 'relational_databases', 'CO_LEARN', '前端状态流和后端数据模型最好一起梳理', 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('backend_service_development', 'transaction_consistency', 'ADVANCE_TO', '服务开发深入后会遇到事务与一致性', 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('api_contract_design', 'network_protocols', 'CO_LEARN', '接口设计与协议语义适合并行补强', 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('automated_testing', 'observability_incident_response', 'BRIDGE', '测试策略会在上线监控与排障中继续发挥作用', 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('devops_delivery', 'cloud_native_basics', 'ADVANCE_TO', '交付流程成熟后会自然走向云原生', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('query_optimization', 'observability_incident_response', 'BRIDGE', '慢查询治理需要监控和排障联动', 110, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('linux_operations', 'devops_delivery', 'CO_LEARN', 'Linux 运维基础和交付能力适合同时练', 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('computer_networks', 'distributed_systems', 'ADVANCE_TO', '网络理解越扎实，分布式系统越容易吃透', 130, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('web_security', 'secure_engineering', 'ADVANCE_TO', '单点安全知识最终要落到工程实践', 140, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('python_data_tools', 'analytics_data_visualization', 'BRIDGE', '数据清洗之后还要能把结果讲出来', 150, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('machine_learning', 'recommendation_systems', 'ADVANCE_TO', '模型基础可以直接延伸到推荐系统', 160, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('llm_applications', 'api_contract_design', 'BRIDGE', '大模型接入最终仍要回到接口与服务设计', 170, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('discrete_mathematics', 'algorithms_analysis', 'ADVANCE_TO', '离散数学会回流强化算法理解', 180, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('compiler_principles', 'operating_systems', 'BRIDGE', '编译、运行时与系统层会在实现细节上相遇', 190, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('open_source_culture', 'collaborative_development', 'CO_LEARN', '开源协作会直接提升多人协作能力', 200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('project_storytelling', 'interview_preparation', 'ADVANCE_TO', '项目叙事整理好后就能进入面试表达', 210, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('task_execution_followup', 'collaborative_development', 'BRIDGE', '任务推进能力需要靠真实协作场景磨出来', 220, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('growth_mindset', 'problem_solving_patterns', 'CO_LEARN', '成长型心态能支撑长期的问题求解训练', 230, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('self_reflection_planning', 'interview_preparation', 'BRIDGE', '复盘规划会直接提升面试复盘质量', 240, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prompt_context_engineering', 'requirement_analysis', 'CO_LEARN', '高质量提示词离不开清晰需求与约束表达', 250, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('vibe_coding_workflows', 'project_storytelling', 'BRIDGE', '快速原型之后仍要补齐方案说明与成果表达', 260, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_pair_programming', 'collaborative_development', 'CO_LEARN', '人与 AI 协作本质上仍需要任务拆分与协作规范', 270, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_codebase_grounding', 'api_contract_design', 'BRIDGE', '仓库上下文对齐离不开接口契约和边界定义', 280, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_coding_agent_tools', 'automated_testing', 'ADVANCE_TO', '编码 Agent 真正可用必须挂在测试与验证链路上', 290, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_code_review_guardrails', 'secure_engineering', 'CO_LEARN', 'AI 输出审查和安全工程检查需要同步建设', 300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_eval_observability', 'observability_incident_response', 'ADVANCE_TO', 'AI 编程链路最终仍要靠评测和运行观测收口', 310, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_programming_engineering', 'prompt_rag_agent', 'BRIDGE', 'AI 编程工程会回流到 Prompt、RAG 与 Agent 方案设计', 320, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tool_schema_design', 'api_contract_design', 'BRIDGE', '工具契约设计和 API 契约设计本质上是同一类边界表达', 330, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('context_window_orchestration', 'data_modeling', 'CO_LEARN', '上下文筛选能力会直接受益于数据结构和信息组织方式', 340, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai_debug_refactor_loops', 'design_patterns_refactoring', 'CO_LEARN', 'AI 重构建议要建立在设计模式和重构判断力之上', 350, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('multi_agent_workflows', 'collaborative_development', 'BRIDGE', '多 Agent 编排和多人协作流程都依赖清晰的任务拆分与交接', 360, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('model_routing_cost_control', 'service_governance_resilience', 'BRIDGE', '模型路由、超时和降级策略需要和服务治理能力一起设计', 370, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (source_node_code, target_node_code, relation_type) DO UPDATE SET
    label = EXCLUDED.label,
    sort_order = EXCLUDED.sort_order,
    updated_at = EXCLUDED.updated_at;

INSERT INTO skill_node_resources(resource_code, node_code, resource_type, title, source_label, duration_label, link_url, sort_order, created_at, updated_at) VALUES
    ('agent-systems-overview', 'ai_coding_agent_systems', 'doc', 'OpenHands 开源编码 Agent', 'GitHub', '长期参考', 'https://github.com/OpenHands/OpenHands', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai-governance-evals', 'ai_engineering_governance', 'doc', 'Evals 指南', 'OpenAI Docs', '长期参考', 'https://platform.openai.com/docs/guides/evals', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai-native-dev-checklist', 'ai_native_development', 'article', 'AI 原生开发分层检查表', '静态推荐', '阅读 18m', 'https://docs.github.com/en/copilot', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai-programming-overview', 'ai_programming_engineering', 'doc', 'GitHub Copilot 文档中心', 'GitHub', '长期参考', 'https://docs.github.com/en/copilot', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('aider-debug-loop', 'ai_debug_refactor_loops', 'doc', 'Aider：终端中的 AI 结对编程', 'GitHub', '长期参考', 'https://github.com/Aider-AI/aider', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('aider-repo', 'vibe_coding_workflows', 'doc', 'Aider：终端中的 AI 结对编程', 'GitHub', '长期参考', 'https://github.com/Aider-AI/aider', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_ai_codebase_grounding_ref', 'ai_codebase_grounding', 'doc', 'Model Context Protocol Introduction', 'MCP', '长期参考', 'https://modelcontextprotocol.io/introduction', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_ai_data_science_ref', 'ai_data_science', 'doc', 'Machine Learning Crash Course', 'Google', '长期参考', 'https://developers.google.com/machine-learning/crash-course', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_ai_pair_programming_ref', 'ai_pair_programming', 'doc', 'GitHub Copilot Docs', 'GitHub Docs', '长期参考', 'https://docs.github.com/en/copilot', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_algorithms_analysis_ref', 'algorithms_analysis', 'doc', 'Algorithms, 4th Edition', 'Princeton', '长期参考', 'https://algs4.cs.princeton.edu/home/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_analytics_data_visualization_ref', 'analytics_data_visualization', 'doc', 'Plotly Python Getting Started', 'Plotly', '长期参考', 'https://plotly.com/python/getting-started/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_api_contract_design_ref', 'api_contract_design', 'doc', 'Best practices for RESTful API design', 'Microsoft Learn', '长期参考', 'https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_applied_cryptography_ref', 'applied_cryptography', 'article', 'What is encryption?', 'Cloudflare', '阅读 10m', 'https://www.cloudflare.com/learning/ssl/what-is-encryption/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_automated_testing_ref', 'automated_testing', 'article', 'The Practical Test Pyramid', 'Martin Fowler', '阅读 18m', 'https://martinfowler.com/articles/practical-test-pyramid.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_big_data_foundations_ref', 'big_data_foundations', 'article', 'What is big data?', 'IBM', '阅读 10m', 'https://www.ibm.com/think/topics/big-data', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_browser_runtime_mechanics_ref', 'browser_runtime_mechanics', 'doc', 'JavaScript Event Loop', 'MDN', '长期参考', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_burnout_prevention_ref', 'burnout_prevention', 'article', 'Burnout prevention and recovery', 'HelpGuide', '阅读 10m', 'https://www.helpguide.org/mental-health/stress/burnout-prevention-and-recovery', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_c_programming_basics_ref', 'c_programming_basics', 'doc', 'C language reference', 'cppreference', '长期参考', 'https://en.cppreference.com/w/c/language.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_career_employment_readiness_ref', 'career_employment_readiness', 'article', 'What Is Career Development?', 'Coursera', '阅读 12m', 'https://www.coursera.org/articles/career-development', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_ci_cd_pipeline_ref', 'ci_cd_pipeline', 'doc', 'Understanding GitHub Actions', 'GitHub Docs', '长期参考', 'https://docs.github.com/en/actions/about-github-actions/understanding-github-actions', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_cloud_native_basics_ref', 'cloud_native_basics', 'doc', 'CNCF Cloud Native Glossary', 'CNCF', '长期参考', 'https://glossary.cncf.io/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_collaborative_development_ref', 'collaborative_development', 'doc', 'Git Tutorials', 'Atlassian', '长期参考', 'https://www.atlassian.com/git/tutorials', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_compiler_principles_ref', 'compiler_principles', 'doc', 'My First Language Frontend with LLVM', 'LLVM', '长期参考', 'https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_computer_organization_ref', 'computer_organization', 'doc', 'Nand to Tetris', 'Nand2Tetris', '长期参考', 'https://www.nand2tetris.org/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_concurrent_programming_basics_ref', 'concurrent_programming_basics', 'doc', 'Concurrency', 'Oracle', '长期参考', 'https://docs.oracle.com/javase/tutorial/essential/concurrency/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_container_kubernetes_ref', 'container_kubernetes', 'doc', 'Kubernetes Basics', 'Kubernetes', '长期参考', 'https://kubernetes.io/docs/tutorials/kubernetes-basics/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_data_cleaning_feature_engineering_ref', 'data_cleaning_feature_engineering', 'doc', 'Preprocessing data', 'scikit-learn', '长期参考', 'https://scikit-learn.org/stable/modules/preprocessing.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_data_database_systems_ref', 'data_database_systems', 'article', 'Database management', 'IBM', '阅读 12m', 'https://www.ibm.com/think/topics/database-management', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_data_modeling_ref', 'data_modeling', 'article', 'What is data modeling?', 'IBM', '阅读 10m', 'https://www.ibm.com/think/topics/data-modeling', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_data_structures_ref', 'data_structures', 'tool', 'VisuAlgo 数据结构可视化', 'VisuAlgo', '互动参考', 'https://visualgo.net/en', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_deep_learning_ref', 'deep_learning', 'doc', 'Learn the Basics', 'PyTorch', '长期参考', 'https://pytorch.org/tutorials/beginner/basics/intro.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_design_patterns_refactoring_ref', 'design_patterns_refactoring', 'doc', 'Design Patterns', 'Refactoring.Guru', '长期参考', 'https://refactoring.guru/design-patterns', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_devops_delivery_ref', 'devops_delivery', 'doc', 'What is DevOps?', 'Atlassian', '长期参考', 'https://www.atlassian.com/devops', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_discrete_mathematics_ref', 'discrete_mathematics', 'doc', 'Mathematics for Computer Science', 'MIT OCW', '长期参考', 'https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_distributed_systems_ref', 'distributed_systems', 'doc', 'MIT 6.824 Distributed Systems', 'MIT', '长期参考', 'https://pdos.csail.mit.edu/6.824/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_domain_modeling_design_ref', 'domain_modeling_design', 'article', 'Domain Model', 'Martin Fowler', '阅读 8m', 'https://martinfowler.com/eaaCatalog/domainModel.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_embedded_systems_ref', 'embedded_systems', 'doc', 'Zephyr Project Introduction', 'Zephyr', '长期参考', 'https://docs.zephyrproject.org/latest/introduction/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_emotion_regulation_ref', 'emotion_regulation', 'article', 'Emotional Intelligence Toolkit', 'HelpGuide', '阅读 12m', 'https://www.helpguide.org/mental-health/wellbeing/emotional-intelligence-toolkit', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_end_to_end_regression_ref', 'end_to_end_regression', 'doc', 'Playwright Introduction', 'Playwright', '长期参考', 'https://playwright.dev/docs/intro', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_engineering_code_conventions_ref', 'engineering_code_conventions', 'doc', 'Google Java Style Guide', 'Google', '长期参考', 'https://google.github.io/styleguide/javaguide.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_engineering_ethics_ref', 'engineering_ethics', 'doc', 'ACM Code of Ethics', 'ACM', '长期参考', 'https://www.acm.org/code-of-ethics', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_file_system_io_ref', 'file_system_io', 'doc', 'File System Intro', 'OSTEP', '长期参考', 'https://pages.cs.wisc.edu/~remzi/OSTEP/file-intro.pdf', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_frontend_component_architecture_ref', 'frontend_component_architecture', 'doc', 'Thinking in React', 'React Docs', '长期参考', 'https://react.dev/learn/thinking-in-react', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_frontend_engineering_ref', 'frontend_engineering', 'doc', 'MDN Learn Web Development', 'MDN', '长期参考', 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_graph_problem_modeling_ref', 'graph_problem_modeling', 'doc', 'Neo4j Graph Modeling', 'Neo4j', '长期参考', 'https://neo4j.com/books/neo4j-graph-modeling/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_habit_energy_management_ref', 'habit_energy_management', 'article', 'Habits Guide: How to Build Good Habits and Break Bad Ones', 'James Clear', '阅读 12m', 'https://jamesclear.com/habits', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_hardware_embedded_ref', 'hardware_embedded', 'doc', 'Arduino Documentation', 'Arduino', '长期参考', 'https://docs.arduino.cc/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_internship_goal_setting_ref', 'internship_goal_setting', 'article', 'How to Write SMART Goals', 'Atlassian', '阅读 8m', 'https://www.atlassian.com/blog/productivity/how-to-write-smart-goals', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_internship_workplace_adaptation_ref', 'internship_workplace_adaptation', 'article', 'Internship tips', 'Indeed', '阅读 10m', 'https://www.indeed.com/career-advice/starting-new-job/internship-tips', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_iot_system_design_ref', 'iot_system_design', 'article', 'What is the Internet of Things?', 'IBM', '阅读 10m', 'https://www.ibm.com/think/topics/internet-of-things', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_java_collections_io_ref', 'java_collections_io', 'doc', 'The Collections Trail', 'Oracle', '长期参考', 'https://docs.oracle.com/javase/tutorial/collections/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_java_programming_ref', 'java_programming', 'doc', 'Java Language Basics', 'Oracle', '长期参考', 'https://docs.oracle.com/javase/tutorial/java/nutsandbolts/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_job_market_research_ref', 'job_market_research', 'article', 'How to Read a Job Description', 'Indeed', '阅读 10m', 'https://www.indeed.com/career-advice/finding-a-job/how-to-read-a-job-description', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_linux_operations_ref', 'linux_operations', 'doc', 'Linux Journey', 'Linux Journey', '长期参考', 'https://linuxjourney.com/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_llm_applications_ref', 'llm_applications', 'doc', 'The Hugging Face LLM Course', 'Hugging Face', '长期参考', 'https://huggingface.co/learn/llm-course/chapter1/1', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_logic_and_proofs_ref', 'logic_and_proofs', 'doc', 'Mathematics for Computer Science Readings', 'MIT OCW', '长期参考', 'https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/pages/readings/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_memory_management_ref', 'memory_management', 'doc', 'Virtual Memory Intro', 'OSTEP', '长期参考', 'https://pages.cs.wisc.edu/~remzi/OSTEP/vm-intro.pdf', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_memory_model_pointers_ref', 'memory_model_pointers', 'doc', 'Pointers in C', 'cppreference', '长期参考', 'https://en.cppreference.com/w/c/language/pointer.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_microcomputer_principles_ref', 'microcomputer_principles', 'doc', 'Computer Organization and Architecture Tutorials', 'GeeksforGeeks', '长期参考', 'https://www.geeksforgeeks.org/computer-organization-architecture/computer-organization-and-architecture-tutorials/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_model_evaluation_validation_ref', 'model_evaluation_validation', 'doc', 'Model selection and evaluation', 'scikit-learn', '长期参考', 'https://scikit-learn.org/stable/model_selection.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_network_protocols_ref', 'network_protocols', 'doc', 'HTTP Overview', 'MDN', '长期参考', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_network_security_ref', 'network_security', 'article', 'What is network security?', 'Cloudflare', '阅读 10m', 'https://www.cloudflare.com/learning/security/what-is-network-security/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_networking_personal_brand_ref', 'networking_personal_brand', 'article', 'What Is Personal Branding?', 'Forbes Books', '阅读 8m', 'https://books.forbes.com/blog/what-is-personal-branding/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_neural_network_training_ref', 'neural_network_training', 'doc', 'Training Neural Networks', 'PyTorch', '长期参考', 'https://pytorch.org/tutorials/beginner/introyt/trainingyt.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_object_oriented_modeling_ref', 'object_oriented_modeling', 'article', 'What is object-oriented programming?', 'IBM', '阅读 12m', 'https://www.ibm.com/think/topics/object-oriented-programming', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_observability_incident_response_ref', 'observability_incident_response', 'doc', 'Site Reliability Engineering', 'Google SRE', '长期参考', 'https://sre.google/sre-book/table-of-contents/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_open_source_culture_ref', 'open_source_culture', 'article', 'How to Contribute to Open Source', 'Open Source Guides', '阅读 15m', 'https://opensource.guide/how-to-contribute/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_probability_inference_ref', 'probability_inference', 'doc', 'Seeing Theory: Basic Probability', 'Brown University', '长期参考', 'https://seeing-theory.brown.edu/basic-probability/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_problem_solving_patterns_ref', 'problem_solving_patterns', 'doc', 'cp-algorithms', 'cp-algorithms', '长期参考', 'https://cp-algorithms.com/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_process_thread_models_ref', 'process_thread_models', 'doc', 'Threads Intro', 'OSTEP', '长期参考', 'https://pages.cs.wisc.edu/~remzi/OSTEP/threads-intro.pdf', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_python_data_tools_ref', 'python_data_tools', 'doc', 'pandas Getting Started', 'pandas', '长期参考', 'https://pandas.pydata.org/docs/getting_started/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_query_optimization_ref', 'query_optimization', 'doc', 'EXPLAIN Output Format', 'MySQL', '长期参考', 'https://dev.mysql.com/doc/refman/8.0/en/explain.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_recommendation_systems_ref', 'recommendation_systems', 'doc', 'Microsoft Recommenders', 'GitHub', '长期参考', 'https://github.com/recommenders-team/recommenders', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_requirement_analysis_ref', 'requirement_analysis', 'article', 'Requirements management guide', 'Atlassian', '阅读 10m', 'https://www.atlassian.com/agile/project-management/requirements', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_secure_engineering_ref', 'secure_engineering', 'doc', 'OWASP Cheat Sheet Series', 'OWASP', '长期参考', 'https://cheatsheetseries.owasp.org/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_self_reflection_planning_ref', 'self_reflection_planning', 'article', 'How to Build a Growth Plan', 'Coursera', '阅读 12m', 'https://www.coursera.org/articles/build-a-growth-plan', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_service_layer_design_ref', 'service_layer_design', 'article', 'Service Layer', 'Martin Fowler', '阅读 10m', 'https://martinfowler.com/eaaCatalog/serviceLayer.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_shell_tooling_automation_ref', 'shell_tooling_automation', 'doc', 'Bash Reference Manual', 'GNU', '长期参考', 'https://www.gnu.org/software/bash/manual/bash.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_software_engineering_delivery_ref', 'software_engineering_delivery', 'doc', 'What is software development?', 'Atlassian', '长期参考', 'https://www.atlassian.com/software-development', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_sql_query_writing_ref', 'sql_query_writing', 'tool', 'SQLBolt', 'SQLBolt', '练习 30m', 'https://sqlbolt.com/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_state_data_flow_ref', 'state_data_flow', 'doc', 'Sharing State Between Components', 'React Docs', '长期参考', 'https://react.dev/learn/sharing-state-between-components', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_statistics_foundation_ref', 'statistics_foundation', 'doc', 'Seeing Theory', 'Brown University', '长期参考', 'https://seeing-theory.brown.edu/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_systems_infrastructure_ref', 'systems_infrastructure', 'doc', 'OSTEP Introduction', 'OSTEP', '长期参考', 'https://pages.cs.wisc.edu/~remzi/OSTEP/intro.pdf', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_task_execution_followup_ref', 'task_execution_followup', 'article', 'Write effective updates to projects, goals, and topics', 'Atlassian Support', '阅读 8m', 'https://support.atlassian.com/platform-experiences/docs/write-effective-updates-to-projects-goals-and-topics/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_teamwork_collaboration_ref', 'teamwork_collaboration', 'article', 'Teamwork examples', 'Atlassian', '阅读 10m', 'https://www.atlassian.com/blog/teamwork/teamwork-examples', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_technology_society_governance_ref', 'technology_society_governance', 'article', 'OECD AI Principles', 'OECD', '阅读 12m', 'https://oecd.ai/en/ai-principles', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_theory_history_ref', 'theory_history', 'doc', 'Computer History Timeline', 'Computer History Museum', '长期参考', 'https://www.computerhistory.org/timeline/computers/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_transaction_consistency_ref', 'transaction_consistency', 'doc', 'InnoDB Transaction Model', 'MySQL', '长期参考', 'https://dev.mysql.com/doc/refman/8.0/en/innodb-transaction-model.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_tree_linear_models_ref', 'tree_linear_models', 'doc', 'Supervised learning', 'scikit-learn', '长期参考', 'https://scikit-learn.org/stable/supervised_learning.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_unit_integration_testing_ref', 'unit_integration_testing', 'doc', 'JUnit 5 User Guide', 'JUnit', '长期参考', 'https://junit.org/junit5/docs/current/user-guide/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_web_security_ref', 'web_security', 'doc', 'OWASP Top 10', 'OWASP', '长期参考', 'https://owasp.org/www-project-top-ten/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_wellbeing_self_management_ref', 'wellbeing_self_management', 'article', 'Mental health at work', 'WHO', '阅读 10m', 'https://www.who.int/news-room/fact-sheets/detail/mental-health-at-work', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('auto_workplace_professionalism_ref', 'workplace_professionalism', 'article', 'Guide to professionalism in the workplace', 'Indeed', '阅读 10m', 'https://www.indeed.com/career-advice/career-development/the-ultimate-guide-to-professionalism', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('career-planning-guide', 'career_positioning', 'doc', '职业规划入门指南', 'Coursera', '长期参考', 'https://www.coursera.org/articles/career-planning', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('computational-thinking-course', 'computational_thinking', 'doc', 'Computational Thinking for Problem Solving', 'University of Pennsylvania', '长期参考', 'https://www.coursera.org/learn/computational-thinking-problem-solving', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('computer-history-timeline', 'cs_history', 'doc', 'Computer History Timeline', 'Computer History Museum', '长期参考', 'https://www.computerhistory.org/timeline/computers/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('context-window-checklist', 'context_window_orchestration', 'article', '上下文筛选与窗口编排清单', '静态推荐', '阅读 15m', 'https://modelcontextprotocol.io/introduction', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('etl-overview', 'data_warehouse_etl', 'doc', 'ETL 与数据仓库基础总览', 'IBM', '长期参考', 'https://www.ibm.com/topics/etl', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('growth-mindset', 'growth_mindset', 'doc', 'Growth Mindset 入门材料', 'Mindset Works', '长期参考', 'https://www.mindsetworks.com/science/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('interview-question-guide', 'interview_preparation', 'doc', '常见面试问题准备指南', 'Indeed', '长期参考', 'https://www.indeed.com/career-advice/interviewing/common-interview-questions-and-answers', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('mdn-http-overview', 'computer_networks', 'doc', 'HTTP 与 Web 通信总览', 'MDN', '长期参考', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ml-crash-course', 'machine_learning', 'doc', 'Machine Learning Crash Course', 'Google', '长期参考', 'https://developers.google.com/machine-learning/crash-course', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('model-routing-litellm', 'model_routing_cost_control', 'doc', 'LiteLLM 路由与成本控制', 'GitHub', '长期参考', 'https://github.com/BerriAI/litellm', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('multi-agent-autogen', 'multi_agent_workflows', 'doc', 'AutoGen 多 Agent 框架', 'GitHub', '长期参考', 'https://github.com/microsoft/autogen', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('mysql-reference', 'relational_databases', 'doc', 'MySQL Reference Manual', 'MySQL', '长期参考', 'https://dev.mysql.com/doc/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('nand2tetris', 'digital_logic', 'doc', 'Nand to Tetris 课程主页', 'Nand2Tetris', '长期参考', 'https://www.nand2tetris.org/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('openai-evals-guide', 'ai_eval_observability', 'doc', 'Evals 指南', 'OpenAI Docs', '长期参考', 'https://platform.openai.com/docs/guides/evals', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('openai-prompt-engineering-guide', 'prompt_context_engineering', 'doc', 'Prompt Engineering Guide', 'OpenAI Docs', '长期参考', 'https://platform.openai.com/docs/guides/prompt-engineering', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('openai-prompt-guide', 'prompt_rag_agent', 'doc', 'Prompt Engineering Guide', 'Prompting Guide', '长期参考', 'https://www.promptingguide.ai/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('openhands-repo', 'ai_coding_agent_tools', 'doc', 'OpenHands 开源编码 Agent', 'GitHub', '长期参考', 'https://github.com/OpenHands/OpenHands', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ossu-cs-roadmap', 'programming_language_foundations', 'doc', 'OSSU Computer Science 路线图', 'OSSU', '长期参考', 'https://github.com/ossu/computer-science', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ostep', 'operating_systems', 'doc', 'Operating Systems: Three Easy Pieces', 'OSTEP', '长期参考', 'https://pages.cs.wisc.edu/~remzi/OSTEP/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prompt-pattern-playbook', 'prompt_pattern_design', 'doc', 'Prompt Engineering Guide', 'OpenAI Docs', '长期参考', 'https://platform.openai.com/docs/guides/prompt-engineering', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('promptfoo-docs', 'ai_code_review_guardrails', 'doc', 'Promptfoo 开源评测与护栏工具', 'GitHub', '长期参考', 'https://github.com/promptfoo/promptfoo', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('resilience-patterns', 'service_governance_resilience', 'doc', 'Resilience Patterns', 'Microsoft', '长期参考', 'https://learn.microsoft.com/en-us/azure/architecture/patterns/category/resiliency', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('resume-guide', 'resume_portfolio', 'doc', '简历写作与作品集整理指南', 'Indeed', '长期参考', 'https://www.indeed.com/career-advice/resumes-cover-letters', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('spring-guides', 'backend_service_development', 'doc', 'Spring 官方 Guides', 'Spring', '长期参考', 'https://spring.io/guides', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('star-storytelling', 'project_storytelling', 'doc', 'STAR 项目叙事模板', 'The Muse', '长期参考', 'https://www.themuse.com/advice/star-interview-method', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('stress-management-guide', 'stress_management', 'doc', '压力管理基础指南', 'Mind', '长期参考', 'https://www.mind.org.uk/information-support/types-of-mental-health-problems/stress/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('system-design-primer', 'software_architecture_design', 'doc', 'System Design Primer', 'GitHub', '长期参考', 'https://github.com/donnemartin/system-design-primer', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tool-schema-guide', 'tool_schema_design', 'doc', 'Tools 指南', 'OpenAI Docs', '长期参考', 'https://platform.openai.com/docs/guides/tools', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('workplace-communication', 'workplace_communication', 'doc', '职场沟通基础手册', 'MindTools', '长期参考', 'https://www.mindtools.com/CommSkll/CommunicationIntro.htm', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai-observability-checklist', 'ai_eval_observability', 'article', 'AI 开发链路评测与留痕清单', '静态推荐', '阅读 15m', 'https://github.com/promptfoo/promptfoo', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai-review-checklist', 'ai_code_review_guardrails', 'article', 'AI 代码审查与回滚检查清单', '静态推荐', '阅读 14m', 'https://github.com/promptfoo/promptfoo', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('analytics-metric-model', 'data_warehouse_etl', 'article', '指标口径与数仓建模入门', '静态推荐', '阅读 16m', 'https://www.getdbt.com/blog/what-is-dimensional-modeling', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('anthropic-prompt-overview', 'prompt_context_engineering', 'doc', 'Prompt Engineering Overview', 'Anthropic Docs', '长期参考', 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('architecture-checklist', 'software_architecture_design', 'article', '系统分层与模块边界检查表', '静态推荐', '阅读 20m', 'https://martinfowler.com/architecture/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('backend-checklist', 'backend_service_development', 'article', '服务分层与工程结构复盘清单', '静态推荐', '阅读 18m', 'https://12factor.net/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('behavioral-interview-notes', 'interview_preparation', 'article', 'STAR 法则与面试复盘模板', '静态推荐', '阅读 20m', 'https://www.themuse.com/advice/star-interview-method', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('copilot-docs-overview', 'ai_native_development', 'doc', 'GitHub Copilot 文档中心', 'GitHub', '长期参考', 'https://docs.github.com/en/copilot', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('cs50', 'programming_language_foundations', 'video', 'CS50 计算机科学导论', 'Harvard', '课程系列', 'https://cs50.harvard.edu/x/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('daily-sync-template', 'workplace_communication', 'article', '日报、周报与同步进度的表达模板', '静态推荐', '阅读 12m', 'https://www.atlassian.com/blog/productivity/how-to-write-status-updates', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('digital-logic-video', 'digital_logic', 'video', '数字逻辑与硬件系统导学', 'Bilibili', '3h 40m', 'https://www.bilibili.com', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('feedback-reframe', 'growth_mindset', 'article', '如何把失败和反馈转化为下一轮行动', '静态推荐', '阅读 14m', 'https://fs.blog/carol-dweck-mindset/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('governance-playbook', 'service_governance_resilience', 'article', '限流、熔断与重试策略速查', '静态推荐', '阅读 15m', 'https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('job-role-notes', 'career_positioning', 'article', '岗位方向拆解与自我评估清单', '静态推荐', '阅读 15m', 'https://www.indeed.com/career-advice/finding-a-job/career-planning-guide', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ml-eval-notes', 'machine_learning', 'article', '特征工程与模型评估入门', '静态推荐', '阅读 22m', 'https://developers.google.com/machine-learning/crash-course/framing/check-your-understanding', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('network-learning', 'computer_networks', 'article', '网络分层与请求路径入门', 'Cloudflare', '阅读 20m', 'https://www.cloudflare.com/learning/network-layer/what-is-a-computer-network/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('openai-tools-guide', 'ai_coding_agent_tools', 'doc', 'Tools 指南', 'OpenAI Docs', '长期参考', 'https://platform.openai.com/docs/guides/tools', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('opensource-history', 'cs_history', 'article', '从技术史到开源协作的脉络速览', '静态推荐', '阅读 16m', 'https://opensource.com/resources/what-open-source', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('os-review', 'operating_systems', 'article', '进程、线程与内存管理复盘提纲', '静态推荐', '阅读 25m', 'https://pages.cs.wisc.edu/~remzi/OSTEP/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('portfolio-checklist', 'resume_portfolio', 'article', '项目经历与作品集表达检查表', '静态推荐', '阅读 18m', 'https://www.indeed.com/career-advice/resumes-cover-letters/how-to-make-a-portfolio', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('problem-decomposition-notes', 'computational_thinking', 'article', '问题抽象与任务拆解练习清单', '静态推荐', '阅读 18m', 'https://developers.google.com/tech-writing', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('project-presentation-checklist', 'project_storytelling', 'article', '项目成果表达与量化结果检查表', '静态推荐', '阅读 12m', 'https://www.indeed.com/career-advice/interviewing/project-based-interview-questions', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rag-agent-notes', 'prompt_rag_agent', 'article', 'RAG 与 Agent 方案拆解清单', '静态推荐', '阅读 22m', 'https://www.pinecone.io/learn/retrieval-augmented-generation/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('sqlbolt', 'relational_databases', 'article', 'SQLBolt 交互式 SQL 练习', 'SQLBolt', '练习 30m', 'https://sqlbolt.com/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('stress-reset-checklist', 'stress_management', 'article', '高压阶段的恢复动作清单', '静态推荐', '阅读 10m', 'https://www.helpguide.org/mental-health/stress/stress-management', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('vibe-coding-playbook', 'vibe_coding_workflows', 'article', '从想法到原型的 Vibe Coding 迭代清单', '静态推荐', '阅读 16m', 'https://docs.github.com/en/copilot', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (resource_code) DO UPDATE SET
    node_code = EXCLUDED.node_code,
    resource_type = EXCLUDED.resource_type,
    title = EXCLUDED.title,
    source_label = EXCLUDED.source_label,
    duration_label = EXCLUDED.duration_label,
    link_url = EXCLUDED.link_url,
    sort_order = EXCLUDED.sort_order,
    updated_at = EXCLUDED.updated_at;
