CREATE TABLE IF NOT EXISTS student_profile_security_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_user_id BIGINT NOT NULL,
    purpose VARCHAR(64) NOT NULL,
    target_email VARCHAR(255) NOT NULL,
    code_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    next_send_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_student_profile_security_code UNIQUE (student_user_id, purpose, target_email),
    CONSTRAINT fk_student_profile_security_user FOREIGN KEY (student_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_student_profile_security_expires_at
    ON student_profile_security_codes(expires_at);
