CREATE TABLE IF NOT EXISTS mentor_service_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentor_user_id BIGINT NOT NULL,
    package_name VARCHAR(40) NOT NULL,
    scene_code VARCHAR(60) NOT NULL,
    scene_label VARCHAR(30) NOT NULL,
    delivery_mode VARCHAR(20) NOT NULL,
    duration_minutes INT,
    price_fen INT NOT NULL DEFAULT 0,
    description VARCHAR(240),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_no INT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_mentor_service_packages_sort UNIQUE (mentor_user_id, sort_no),
    CONSTRAINT fk_mentor_service_packages_mentor FOREIGN KEY (mentor_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_mentor_service_packages_enabled
    ON mentor_service_packages(mentor_user_id, enabled, sort_no);
