CREATE TABLE mentor_schedule_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentor_user_id BIGINT NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    booked_order_no VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_mentor_schedule_slots UNIQUE (mentor_user_id, start_at, end_at),
    CONSTRAINT fk_mentor_schedule_slots_mentor FOREIGN KEY (mentor_user_id) REFERENCES users(id)
);

CREATE INDEX idx_mentor_schedule_slots_mentor_time ON mentor_schedule_slots(mentor_user_id, start_at);
CREATE INDEX idx_mentor_schedule_slots_status_time ON mentor_schedule_slots(status, start_at);
