CREATE TABLE certification_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    user_role VARCHAR(20) NOT NULL,
    real_name VARCHAR(100) NOT NULL,
    company_name VARCHAR(200),
    job_title VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    review_note VARCHAR(1000),
    reviewed_by BIGINT,
    reviewed_at TIMESTAMPTZ,
    previous_submission_id BIGINT,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_certification_submissions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_certification_submissions_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id),
    CONSTRAINT fk_certification_submissions_previous FOREIGN KEY (previous_submission_id) REFERENCES certification_submissions(id)
);

CREATE INDEX idx_certification_submissions_user ON certification_submissions(user_id, is_current, submitted_at);
CREATE INDEX idx_certification_submissions_status ON certification_submissions(status, submitted_at);

CREATE TABLE certification_submission_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    storage_bucket VARCHAR(100) NOT NULL,
    object_key VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100),
    size_bytes BIGINT NOT NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    delete_reason VARCHAR(100),
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_certification_assets_object_key UNIQUE (object_key),
    CONSTRAINT fk_certification_assets_submission FOREIGN KEY (submission_id) REFERENCES certification_submissions(id)
);

CREATE INDEX idx_certification_assets_submission ON certification_submission_assets(submission_id, lifecycle_status);

ALTER TABLE mentor_profiles ALTER COLUMN approval_status SET DEFAULT 'PENDING';
ALTER TABLE enterprise_profiles ALTER COLUMN approval_status SET DEFAULT 'PENDING';
