CREATE TABLE IF NOT EXISTS feature_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flag_key VARCHAR(100) NOT NULL,
    flag_value VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_feature_flags_key UNIQUE (flag_key)
);

CREATE INDEX IF NOT EXISTS idx_feature_flags_updated_at ON feature_flags(updated_at);
