CREATE TABLE IF NOT EXISTS notification_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(64) NOT NULL,
    type VARCHAR(60) NOT NULL,
    category VARCHAR(32) NOT NULL,
    source_type VARCHAR(60),
    source_id VARCHAR(64),
    actor_user_id BIGINT,
    priority VARCHAR(20) NOT NULL,
    dedupe_key VARCHAR(160),
    payload_json TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_notification_events_event_id UNIQUE (event_id),
    CONSTRAINT uq_notification_events_dedupe_key UNIQUE (dedupe_key),
    CONSTRAINT fk_notification_events_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_notification_events_category_time ON notification_events(category, occurred_at, id);
CREATE INDEX IF NOT EXISTS idx_notification_events_source ON notification_events(source_type, source_id, occurred_at, id);
