CREATE TABLE IF NOT EXISTS mentor_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_user_id BIGINT NOT NULL,
    mentor_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mentor_favorites_student_mentor UNIQUE (student_user_id, mentor_user_id),
    CONSTRAINT fk_mentor_favorites_student FOREIGN KEY (student_user_id) REFERENCES users(id),
    CONSTRAINT fk_mentor_favorites_mentor FOREIGN KEY (mentor_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_mentor_favorites_student_time
    ON mentor_favorites(student_user_id, created_at, id);

CREATE INDEX IF NOT EXISTS idx_mentor_favorites_mentor_time
    ON mentor_favorites(mentor_user_id, created_at, id);
