CREATE TABLE IF NOT EXISTS ai_quota_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier VARCHAR(20) NOT NULL,
    task_type VARCHAR(30) NOT NULL,
    scene_code VARCHAR(60),
    daily_free_limit INT NOT NULL,
    points_per_call INT NOT NULL,
    daily_max_limit INT NOT NULL,
    model_preference VARCHAR(50),
    max_input_tokens INT NOT NULL DEFAULT 4000,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ai_quota_policies_tier_task_scene UNIQUE (tier, task_type, scene_code)
);

CREATE INDEX IF NOT EXISTS idx_ai_quota_policies_lookup
    ON ai_quota_policies(tier, task_type, scene_code);

INSERT INTO ai_quota_policies(
    tier,
    task_type,
    scene_code,
    daily_free_limit,
    points_per_call,
    daily_max_limit,
    model_preference,
    max_input_tokens,
    created_at,
    updated_at
)
VALUES
    ('FREE', 'RESUME', NULL, 3, 10, 20, 'mock-economy-model', 4000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('FREE', 'INTERVIEW_TEXT', NULL, 5, 5, 30, 'mock-economy-model', 4000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('FREE', 'COMMUNITY_REPLY', NULL, 5, 2, 20, 'mock-economy-model', 4000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('FREE', 'COMMUNITY_REPLY', 'COMMUNITY_PRE_ANSWER', 5, 2, 20, 'mock-economy-model', 4000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('FREE', 'COMMUNITY_REPLY', 'MENTOR_PREP_SHEET_GENERATE', 2, 6, 8, 'mock-economy-model', 8000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('FREE', 'ICEBREAK', NULL, 3, 3, 15, 'mock-economy-model', 4000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('FREE', 'TTS', NULL, 2, 5, 10, 'mock-economy-model', 2000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PREMIUM', 'RESUME', NULL, -1, 0, -1, 'mock-premium-model', 12000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PREMIUM', 'INTERVIEW_TEXT', NULL, -1, 0, -1, 'mock-premium-model', 12000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PREMIUM', 'COMMUNITY_REPLY', NULL, -1, 0, -1, 'mock-premium-model', 12000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PREMIUM', 'COMMUNITY_REPLY', 'COMMUNITY_PRE_ANSWER', -1, 0, -1, 'mock-premium-model', 12000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PREMIUM', 'COMMUNITY_REPLY', 'MENTOR_PREP_SHEET_GENERATE', -1, 0, -1, 'mock-premium-model', 16000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PREMIUM', 'ICEBREAK', NULL, -1, 0, -1, 'mock-premium-model', 12000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PREMIUM', 'TTS', NULL, -1, 0, -1, 'mock-premium-model', 4000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
