CREATE TABLE IF NOT EXISTS prompt_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type VARCHAR(40) NOT NULL,
    template_name VARCHAR(80) NOT NULL,
    version_no INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    template_format VARCHAR(32) NOT NULL DEFAULT 'TEXT',
    content TEXT NOT NULL,
    description VARCHAR(255),
    variables_json TEXT,
    bundle_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_prompt_templates_version UNIQUE (task_type, template_name, version_no)
);

CREATE INDEX IF NOT EXISTS idx_prompt_templates_task_name_status
    ON prompt_templates(task_type, template_name, status, version_no);
