CREATE TABLE IF NOT EXISTS ai_scene_route_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_code VARCHAR(80) NOT NULL,
    task_type VARCHAR(40) NOT NULL,
    scene_code VARCHAR(60) NOT NULL,
    user_tier VARCHAR(20) NOT NULL DEFAULT 'FREE',
    strategy_type VARCHAR(20) NOT NULL DEFAULT 'SINGLE',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    notes VARCHAR(255),
    extra_config_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ai_scene_route_policies_code UNIQUE (policy_code),
    CONSTRAINT uq_ai_scene_route_policies_scene_tier UNIQUE (task_type, scene_code, user_tier)
);

CREATE INDEX IF NOT EXISTS idx_ai_scene_route_policies_lookup
    ON ai_scene_route_policies(task_type, scene_code, user_tier, enabled);
