CREATE TABLE IF NOT EXISTS ai_provider_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_code VARCHAR(60) NOT NULL,
    provider_type VARCHAR(40) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    base_url VARCHAR(255) NOT NULL,
    api_key_ciphertext TEXT,
    api_key_masked VARCHAR(80),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    timeout_ms INT NOT NULL DEFAULT 15000,
    max_retries INT NOT NULL DEFAULT 1,
    cost_per_1k_input DECIMAL(10, 6) NOT NULL DEFAULT 0,
    cost_per_1k_output DECIMAL(10, 6) NOT NULL DEFAULT 0,
    extra_config_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ai_provider_configs_code UNIQUE (provider_code)
);
