CREATE TABLE IF NOT EXISTS ai_provider_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_config_id BIGINT NOT NULL,
    model_code VARCHAR(120) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    input_cost_per_1k DECIMAL(10, 6) NOT NULL DEFAULT 0,
    output_cost_per_1k DECIMAL(10, 6) NOT NULL DEFAULT 0,
    context_window INT,
    max_output_tokens INT,
    supported_task_types_json TEXT,
    notes VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ai_provider_models_provider_model UNIQUE (provider_config_id, model_code),
    CONSTRAINT fk_ai_provider_models_provider FOREIGN KEY (provider_config_id) REFERENCES ai_provider_configs(id)
);

CREATE INDEX IF NOT EXISTS idx_ai_provider_models_provider_enabled
    ON ai_provider_models(provider_config_id, enabled, model_code);
