CREATE TABLE IF NOT EXISTS ai_model_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_code VARCHAR(60) NOT NULL,
    task_type VARCHAR(40) NOT NULL,
    scene_code VARCHAR(60),
    scene_route_policy_id BIGINT,
    provider_config_id BIGINT NOT NULL,
    model_name VARCHAR(120) NOT NULL,
    priority_no INT NOT NULL DEFAULT 100,
    candidate_weight INT NOT NULL DEFAULT 100,
    execution_mode VARCHAR(32) NOT NULL DEFAULT 'SYNC_BLOCKING',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    temperature DECIMAL(5, 2) NOT NULL DEFAULT 0.20,
    system_prompt TEXT,
    prompt_template_name VARCHAR(80),
    extra_config_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ai_model_routes_code UNIQUE (route_code),
    CONSTRAINT fk_ai_model_routes_policy FOREIGN KEY (scene_route_policy_id) REFERENCES ai_scene_route_policies(id),
    CONSTRAINT fk_ai_model_routes_provider FOREIGN KEY (provider_config_id) REFERENCES ai_provider_configs(id)
);

CREATE INDEX IF NOT EXISTS idx_ai_model_routes_task_scene_priority
    ON ai_model_routes(task_type, scene_code, enabled, priority_no);

CREATE INDEX IF NOT EXISTS idx_ai_model_routes_prompt_template
    ON ai_model_routes(task_type, prompt_template_name);

CREATE INDEX IF NOT EXISTS idx_ai_model_routes_policy_priority
    ON ai_model_routes(scene_route_policy_id, enabled, priority_no);
