CREATE TABLE IF NOT EXISTS consult_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    student_user_id BIGINT NOT NULL,
    mentor_user_id BIGINT NOT NULL,
    amount_fen INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    question_text TEXT,
    paid_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_consult_orders_order_no UNIQUE (order_no),
    CONSTRAINT fk_consult_orders_student FOREIGN KEY (student_user_id) REFERENCES users(id),
    CONSTRAINT fk_consult_orders_mentor FOREIGN KEY (mentor_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_consult_orders_student_time
    ON consult_orders(student_user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_consult_orders_mentor_time
    ON consult_orders(mentor_user_id, created_at);
