CREATE TABLE IF NOT EXISTS content_moderation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    target_id VARCHAR(100),
    risk_level VARCHAR(20) NOT NULL,
    action VARCHAR(20) NOT NULL,
    reason_code VARCHAR(100) NOT NULL,
    masked_text TEXT,
    operator_user_id BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_moderation_trace
    ON content_moderation_events(trace_id);

CREATE INDEX IF NOT EXISTS idx_moderation_target
    ON content_moderation_events(target_type, target_id, created_at);

CREATE TABLE IF NOT EXISTS content_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL,
    target_type VARCHAR(20) NOT NULL,
    target_id VARCHAR(100) NOT NULL,
    reason_code VARCHAR(50) NOT NULL,
    detail VARCHAR(1000),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    latest_action VARCHAR(50) NOT NULL DEFAULT 'NONE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMPTZ,
    CONSTRAINT uq_content_reports_dedupe UNIQUE (reporter_user_id, target_type, target_id, reason_code)
);

CREATE INDEX IF NOT EXISTS idx_content_reports_reporter
    ON content_reports(reporter_user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_content_reports_target
    ON content_reports(target_type, target_id, status);
