ALTER TABLE consult_orders
    ADD COLUMN IF NOT EXISTS appointment_start_at TIMESTAMPTZ;

ALTER TABLE consult_orders
    ADD COLUMN IF NOT EXISTS appointment_end_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS payment_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    channel VARCHAR(20) NOT NULL,
    mode VARCHAR(20) NOT NULL,
    provider_trade_no VARCHAR(128),
    amount_fen INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'INIT',
    idempotency_key VARCHAR(128),
    raw_callback TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_payment_records_idempotency UNIQUE (idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_payment_records_order_time
    ON payment_records(order_no, created_at);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    operator_user_id BIGINT NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    target_type VARCHAR(30),
    target_id VARCHAR(100),
    detail_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_trace
    ON audit_logs(trace_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_action_time
    ON audit_logs(action_type, created_at);
