CREATE TABLE IF NOT EXISTS notification_dispatch_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(64) NOT NULL,
    notification_id BIGINT NOT NULL,
    event_id VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    channel VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 3,
    next_run_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_owner VARCHAR(80),
    lease_expires_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    acked_at TIMESTAMPTZ,
    failed_at TIMESTAMPTZ,
    error_code VARCHAR(40),
    error_message VARCHAR(500),
    payload_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_notification_dispatch_jobs_job_id UNIQUE (job_id),
    CONSTRAINT fk_notification_dispatch_jobs_notification FOREIGN KEY (notification_id) REFERENCES notifications(id),
    CONSTRAINT fk_notification_dispatch_jobs_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_notification_dispatch_jobs_status_run
    ON notification_dispatch_jobs(status, next_run_at, id);

CREATE INDEX IF NOT EXISTS idx_notification_dispatch_jobs_user_channel
    ON notification_dispatch_jobs(user_id, channel, status, id);

CREATE TABLE IF NOT EXISTS notification_dispatch_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    attempt_no INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    request_snapshot_json TEXT,
    response_snapshot_json TEXT,
    error_code VARCHAR(40),
    error_message VARCHAR(500),
    latency_ms BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_dispatch_attempts_job FOREIGN KEY (job_id) REFERENCES notification_dispatch_jobs(id)
);

CREATE INDEX IF NOT EXISTS idx_notification_dispatch_attempts_job
    ON notification_dispatch_attempts(job_id, created_at, id);
