CREATE TABLE IF NOT EXISTS student_recommendation_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_user_id BIGINT NOT NULL,
    content_text TEXT NOT NULL,
    target_position VARCHAR(100),
    skill_tags_json TEXT,
    portrait_tags_json TEXT,
    latest_resume_record_id BIGINT,
    latest_resume_target_role VARCHAR(100),
    latest_resume_summary TEXT,
    latest_resume_suggestions_json TEXT,
    latest_interview_session_id VARCHAR(64),
    latest_interview_target_role VARCHAR(100),
    latest_interview_weaknesses_json TEXT,
    latest_interview_suggestions_json TEXT,
    signal_flags_json TEXT,
    content_hash CHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_student_recommendation_snapshots_student UNIQUE (student_user_id),
    CONSTRAINT fk_student_recommendation_snapshots_student FOREIGN KEY (student_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_student_recommendation_snapshots_hash
    ON student_recommendation_snapshots(content_hash);

CREATE TABLE IF NOT EXISTS mentor_recommendation_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentor_user_id BIGINT NOT NULL,
    content_text TEXT NOT NULL,
    expertise_tags_json TEXT,
    service_scenes_json TEXT,
    quality_score INT NOT NULL DEFAULT 0,
    price_fen INT NOT NULL DEFAULT 0,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    content_hash CHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mentor_recommendation_snapshots_mentor UNIQUE (mentor_user_id),
    CONSTRAINT fk_mentor_recommendation_snapshots_mentor FOREIGN KEY (mentor_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_mentor_recommendation_snapshots_hash
    ON mentor_recommendation_snapshots(content_hash);

CREATE TABLE IF NOT EXISTS recommendation_embedding_vectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(30) NOT NULL,
    entity_id BIGINT NOT NULL,
    model_code VARCHAR(60) NOT NULL,
    vector_dim INT NOT NULL,
    vector_json TEXT NOT NULL,
    content_hash CHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_recommendation_embedding_vectors_entity UNIQUE (entity_type, entity_id, model_code)
);

CREATE INDEX IF NOT EXISTS idx_recommendation_embedding_vectors_hash
    ON recommendation_embedding_vectors(content_hash);

CREATE TABLE IF NOT EXISTS mentor_recommendation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_user_id BIGINT NOT NULL,
    scene VARCHAR(60),
    keyword VARCHAR(255),
    expertise VARCHAR(255),
    filter_payload_json TEXT NOT NULL,
    recall_model_code VARCHAR(60) NOT NULL,
    rerank_version VARCHAR(60) NOT NULL,
    weak_signal BOOLEAN NOT NULL DEFAULT FALSE,
    candidate_count INT NOT NULL DEFAULT 0,
    recalled_count INT NOT NULL DEFAULT 0,
    top_mentor_user_ids_json TEXT NOT NULL,
    basis_summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mentor_recommendation_runs_student FOREIGN KEY (student_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_mentor_recommendation_runs_student_time
    ON mentor_recommendation_runs(student_user_id, created_at);

CREATE TABLE IF NOT EXISTS mentor_recommendation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    mentor_user_id BIGINT NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    stage_rank INT,
    score DECIMAL(10, 6),
    detail_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mentor_recommendation_events_run FOREIGN KEY (run_id) REFERENCES mentor_recommendation_runs(id),
    CONSTRAINT fk_mentor_recommendation_events_mentor FOREIGN KEY (mentor_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_mentor_recommendation_events_run
    ON mentor_recommendation_events(run_id, created_at);

CREATE INDEX IF NOT EXISTS idx_mentor_recommendation_events_mentor
    ON mentor_recommendation_events(mentor_user_id, created_at);
