CREATE TABLE IF NOT EXISTS daily_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_code VARCHAR(50) NOT NULL,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    points INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_daily_tasks_task_code UNIQUE (task_code)
);

CREATE TABLE IF NOT EXISTS checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_user_id BIGINT NOT NULL,
    checkin_date DATE NOT NULL,
    streak_count INT NOT NULL,
    points_earned INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_checkins_user_date UNIQUE (student_user_id, checkin_date),
    CONSTRAINT fk_checkins_user FOREIGN KEY (student_user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS points_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_user_id BIGINT NOT NULL,
    delta_points INT NOT NULL,
    reason_code VARCHAR(50) NOT NULL,
    balance_after INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_points_ledger_user FOREIGN KEY (student_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_points_ledger_student_time
    ON points_ledger(student_user_id, created_at);

CREATE TABLE IF NOT EXISTS growth_checkin_reward_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reward_code VARCHAR(50) NOT NULL,
    streak_days INT NOT NULL,
    bonus_points INT NOT NULL,
    reward_title VARCHAR(100) NOT NULL,
    reward_description VARCHAR(255),
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_growth_checkin_reward_rules_code UNIQUE (reward_code),
    CONSTRAINT uq_growth_checkin_reward_rules_streak UNIQUE (streak_days)
);

INSERT INTO daily_tasks(task_code, title, description, points, is_active, sort_order, created_at, updated_at)
SELECT 'TASK_RESUME_OPTIMIZE', '完成一次简历优化', '针对目标岗位优化一版简历内容并记录调整点。', 10, TRUE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM daily_tasks WHERE task_code = 'TASK_RESUME_OPTIMIZE');

INSERT INTO daily_tasks(task_code, title, description, points, is_active, sort_order, created_at, updated_at)
SELECT 'TASK_SKILL_PROGRESS', '点亮一个技能节点', '在技能树中完成一个学习节点更新，保持成长连续性。', 8, TRUE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM daily_tasks WHERE task_code = 'TASK_SKILL_PROGRESS');

INSERT INTO daily_tasks(task_code, title, description, points, is_active, sort_order, created_at, updated_at)
SELECT 'TASK_COMMUNITY_INTERACT', '参与一次社区互动', '阅读并发布一条有价值的社区互动内容。', 6, TRUE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM daily_tasks WHERE task_code = 'TASK_COMMUNITY_INTERACT');

INSERT INTO growth_checkin_reward_rules(
    reward_code,
    streak_days,
    bonus_points,
    reward_title,
    reward_description,
    is_enabled,
    sort_order,
    created_at,
    updated_at
)
SELECT 'CHECKIN_STREAK_3', 3, 6, '三日连签奖励', '连续签到 3 天可额外获得 6 积分。', TRUE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM growth_checkin_reward_rules WHERE reward_code = 'CHECKIN_STREAK_3');

INSERT INTO growth_checkin_reward_rules(
    reward_code,
    streak_days,
    bonus_points,
    reward_title,
    reward_description,
    is_enabled,
    sort_order,
    created_at,
    updated_at
)
SELECT 'CHECKIN_STREAK_7', 7, 14, '七日连签奖励', '连续签到 7 天可额外获得 14 积分。', TRUE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM growth_checkin_reward_rules WHERE reward_code = 'CHECKIN_STREAK_7');

INSERT INTO growth_checkin_reward_rules(
    reward_code,
    streak_days,
    bonus_points,
    reward_title,
    reward_description,
    is_enabled,
    sort_order,
    created_at,
    updated_at
)
SELECT 'CHECKIN_STREAK_14', 14, 30, '十四日连签奖励', '连续签到 14 天可额外获得 30 积分。', TRUE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM growth_checkin_reward_rules WHERE reward_code = 'CHECKIN_STREAK_14');
