CREATE TABLE IF NOT EXISTS ai_async_task_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    task_type VARCHAR(40) NOT NULL,
    scene_code VARCHAR(60),
    route_code VARCHAR(60),
    execution_mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    provider_code VARCHAR(60),
    provider_type VARCHAR(40),
    model_name VARCHAR(120),
    prompt_template_name VARCHAR(80),
    prompt_template_version_no INT,
    input_snapshot_json TEXT,
    context_json TEXT,
    prompt_snapshot_json TEXT,
    route_snapshot_json TEXT,
    result_summary TEXT,
    result_payload_json TEXT,
    error_code VARCHAR(40),
    error_message VARCHAR(500),
    current_attempt INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 3,
    next_run_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_owner VARCHAR(80),
    lease_expires_at TIMESTAMPTZ,
    queued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ai_async_task_jobs_task_id UNIQUE (task_id),
    CONSTRAINT fk_ai_async_task_jobs_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_ai_async_task_jobs_status_next_run
    ON ai_async_task_jobs(status, next_run_at, id);

CREATE INDEX IF NOT EXISTS idx_ai_async_task_jobs_user_created
    ON ai_async_task_jobs(user_id, created_at, id);

CREATE INDEX IF NOT EXISTS idx_ai_async_task_jobs_task_scene
    ON ai_async_task_jobs(task_type, scene_code, status, id);

CREATE TABLE IF NOT EXISTS ai_async_task_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(64) NOT NULL,
    task_job_id BIGINT NOT NULL,
    task_id VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    event_type VARCHAR(60) NOT NULL,
    delivery_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    payload_json TEXT,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ai_async_task_events_event_id UNIQUE (event_id),
    CONSTRAINT fk_ai_async_task_events_job FOREIGN KEY (task_job_id) REFERENCES ai_async_task_jobs(id),
    CONSTRAINT fk_ai_async_task_events_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_ai_async_task_events_delivery_status
    ON ai_async_task_events(delivery_status, created_at, id);

CREATE INDEX IF NOT EXISTS idx_ai_async_task_events_task_id
    ON ai_async_task_events(task_id, created_at, id);
