ALTER TABLE bounty_submissions
    ADD COLUMN IF NOT EXISTS contact_intent VARCHAR(80),
    ADD COLUMN IF NOT EXISTS reject_template VARCHAR(160),
    ADD COLUMN IF NOT EXISTS review_note TEXT;

CREATE TABLE IF NOT EXISTS bounty_submission_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    actor_user_id BIGINT,
    event_type VARCHAR(40) NOT NULL,
    comment_text VARCHAR(500),
    contact_intent VARCHAR(80),
    reject_template VARCHAR(160),
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bounty_submission_events_submission FOREIGN KEY (submission_id) REFERENCES bounty_submissions(id),
    CONSTRAINT fk_bounty_submission_events_task FOREIGN KEY (task_id) REFERENCES bounty_tasks(id),
    CONSTRAINT fk_bounty_submission_events_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_bounty_submission_events_submission_time
    ON bounty_submission_events(submission_id, created_at, id);

CREATE INDEX IF NOT EXISTS idx_bounty_submission_events_task_time
    ON bounty_submission_events(task_id, created_at, id);

INSERT INTO bounty_submission_events (
    submission_id,
    task_id,
    actor_user_id,
    event_type,
    note,
    created_at
)
SELECT submission.id,
       submission.task_id,
       submission.student_user_id,
       'SUBMITTED',
       CASE
           WHEN submission.content_text IS NULL OR char_length(trim(submission.content_text)) = 0 THEN NULL
           ELSE left(trim(submission.content_text), 255)
       END,
       submission.created_at
FROM bounty_submissions submission;

INSERT INTO bounty_submission_events (
    submission_id,
    task_id,
    actor_user_id,
    event_type,
    comment_text,
    created_at
)
SELECT submission.id,
       submission.task_id,
       submission.reviewer_user_id,
       CASE
           WHEN submission.status = 'ACCEPTED' THEN 'CONTACT_SENT'
           ELSE 'REJECT_SENT'
       END,
       submission.review_comment,
       submission.reviewed_at
FROM bounty_submissions submission
WHERE submission.status IN ('ACCEPTED', 'REJECTED')
  AND submission.reviewed_at IS NOT NULL;

INSERT INTO bounty_submission_events (
    submission_id,
    task_id,
    actor_user_id,
    event_type,
    note,
    created_at
)
SELECT submission.id,
       task.id,
       task.enterprise_user_id,
       'TASK_CLOSED_AFTER_ACCEPT',
       '任务已结束，当前结果留痕已固定在工作区中。',
       task.closed_at
FROM bounty_tasks task
JOIN bounty_submissions submission
  ON submission.id = task.accepted_submission_id
WHERE task.accepted_submission_id IS NOT NULL
  AND task.closed_at IS NOT NULL;

ALTER TABLE bounty_submissions
    DROP COLUMN IF EXISTS internal_note;
