ALTER TABLE mentor_profiles
    ADD COLUMN IF NOT EXISTS avg_rating DECIMAL(3, 2) NOT NULL DEFAULT 0.00;

CREATE TABLE IF NOT EXISTS mentor_withdrawal_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentor_user_id BIGINT NOT NULL,
    amount_fen INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    note VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mentor_withdrawal_requests_user FOREIGN KEY (mentor_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_mentor_withdrawal_requests_user_time
    ON mentor_withdrawal_requests(mentor_user_id, created_at);
