CREATE TABLE IF NOT EXISTS consult_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    student_user_id BIGINT NOT NULL,
    mentor_user_id BIGINT NOT NULL,
    rating SMALLINT NOT NULL,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_consult_reviews_order_no UNIQUE (order_no),
    CONSTRAINT fk_consult_reviews_student FOREIGN KEY (student_user_id) REFERENCES users(id),
    CONSTRAINT fk_consult_reviews_mentor FOREIGN KEY (mentor_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_consult_reviews_mentor_time
    ON consult_reviews(mentor_user_id, created_at);
