ALTER TABLE consult_orders
    ADD COLUMN IF NOT EXISTS scene_code VARCHAR(60);

ALTER TABLE consult_orders
    ADD COLUMN IF NOT EXISTS source_page VARCHAR(80);

ALTER TABLE consult_orders
    ADD COLUMN IF NOT EXISTS question_payload_json TEXT;

ALTER TABLE consult_orders
    ADD COLUMN IF NOT EXISTS problem_summary TEXT;

ALTER TABLE consult_orders
    ADD COLUMN IF NOT EXISTS core_questions_json TEXT;

ALTER TABLE consult_orders
    ADD COLUMN IF NOT EXISTS expected_outcomes_json TEXT;

ALTER TABLE consult_orders
    ADD COLUMN IF NOT EXISTS selected_material_types VARCHAR(255);

ALTER TABLE consult_orders
    ADD COLUMN IF NOT EXISTS prep_sheet_snapshot_json TEXT;

ALTER TABLE consult_orders
    ADD COLUMN IF NOT EXISTS service_package_snapshot_json TEXT;

CREATE TABLE IF NOT EXISTS consult_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    sender_user_id BIGINT NOT NULL,
    sender_role VARCHAR(20) NOT NULL,
    message_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_consult_messages_sender FOREIGN KEY (sender_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_consult_messages_order_time
    ON consult_messages(order_no, created_at);

CREATE TABLE IF NOT EXISTS consult_order_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    uploaded_by_user_id BIGINT NOT NULL,
    attachment_type VARCHAR(40) NOT NULL,
    slot_code VARCHAR(60) NOT NULL,
    source_stage VARCHAR(30) NOT NULL DEFAULT 'ORDER_CREATE',
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT NOT NULL,
    storage_bucket VARCHAR(120) NOT NULL,
    object_key VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'CURRENT',
    replaced_attachment_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_consult_order_attachments_uploader FOREIGN KEY (uploaded_by_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_consult_order_attachments_order_time
    ON consult_order_attachments(order_no, created_at);

CREATE INDEX IF NOT EXISTS idx_consult_order_attachments_order_lifecycle
    ON consult_order_attachments(order_no, lifecycle_status);

CREATE INDEX IF NOT EXISTS idx_consult_order_attachments_slot
    ON consult_order_attachments(order_no, slot_code, lifecycle_status);
