CREATE TABLE IF NOT EXISTS sensitive_terms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term VARCHAR(200) NOT NULL,
    term_type VARCHAR(50) NOT NULL DEFAULT 'OTHER',
    risk_level VARCHAR(20) NOT NULL,
    action VARCHAR(20) NOT NULL,
    source_scope VARCHAR(50) NOT NULL,
    is_whitelist SMALLINT NOT NULL DEFAULT 0,
    enabled SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sensitive_terms_scope UNIQUE (term, source_scope, is_whitelist)
);

CREATE INDEX IF NOT EXISTS idx_sensitive_terms_scope_enabled
    ON sensitive_terms(source_scope, enabled, is_whitelist);

CREATE INDEX IF NOT EXISTS idx_sensitive_terms_type_enabled
    ON sensitive_terms(term_type, enabled, is_whitelist);

CREATE TABLE IF NOT EXISTS moderation_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_key VARCHAR(100) NOT NULL,
    policy_value VARCHAR(500) NOT NULL,
    description VARCHAR(500),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_moderation_policies_key UNIQUE (policy_key)
);

INSERT INTO moderation_policies(policy_key, policy_value, description, updated_by, updated_at)
VALUES ('ai_input_enabled', 'true', 'AI 输入审查开关', 0, CURRENT_TIMESTAMP)
ON CONFLICT (policy_key) DO NOTHING;

INSERT INTO moderation_policies(policy_key, policy_value, description, updated_by, updated_at)
VALUES ('ai_output_enabled', 'true', 'AI 输出审查开关', 0, CURRENT_TIMESTAMP)
ON CONFLICT (policy_key) DO NOTHING;

INSERT INTO moderation_policies(policy_key, policy_value, description, updated_by, updated_at)
VALUES ('community_strict_review_enabled', 'true', '社区内容审查开关', 0, CURRENT_TIMESTAMP)
ON CONFLICT (policy_key) DO NOTHING;

INSERT INTO moderation_policies(policy_key, policy_value, description, updated_by, updated_at)
VALUES ('auto_hide_report_threshold', '3', '举报自动隐藏阈值', 0, CURRENT_TIMESTAMP)
ON CONFLICT (policy_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS content_report_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL,
    operator_user_id BIGINT NOT NULL,
    decision VARCHAR(20) NOT NULL,
    action VARCHAR(50) NOT NULL,
    comment VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_content_report_actions_report FOREIGN KEY (report_id) REFERENCES content_reports(id),
    CONSTRAINT fk_content_report_actions_user FOREIGN KEY (operator_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_content_report_actions_report
    ON content_report_actions(report_id, created_at);
