CREATE TABLE IF NOT EXISTS skill_node_resources (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    resource_code VARCHAR(100) NOT NULL,
    node_code VARCHAR(100) NOT NULL,
    resource_type VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    source_label VARCHAR(100) NOT NULL,
    duration_label VARCHAR(50) NOT NULL,
    link_url VARCHAR(500) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_skill_node_resources_code UNIQUE (resource_code),
    CONSTRAINT fk_skill_node_resources_node FOREIGN KEY (node_code) REFERENCES skills(node_code)
);

INSERT INTO skill_node_resources(
    resource_code,
    node_code,
    resource_type,
    title,
    source_label,
    duration_label,
    link_url,
    sort_order,
    created_at,
    updated_at
) VALUES
('ossu-cs-roadmap', 'programming_language_foundations', 'doc', 'OSSU Computer Science 路线图', 'OSSU', '长期参考', 'https://github.com/ossu/computer-science', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('cs50', 'programming_language_foundations', 'video', 'CS50 计算机科学导论', 'Harvard', '课程系列', 'https://cs50.harvard.edu/x/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('spring-guides', 'backend_service_development', 'doc', 'Spring 官方 Guides', 'Spring', '长期参考', 'https://spring.io/guides', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('backend-checklist', 'backend_service_development', 'article', '服务分层与工程结构复盘清单', '静态推荐', '阅读 18m', 'https://12factor.net/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mysql-reference', 'relational_databases', 'doc', 'MySQL Reference Manual', 'MySQL', '长期参考', 'https://dev.mysql.com/doc/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('sqlbolt', 'relational_databases', 'article', 'SQLBolt 交互式 SQL 练习', 'SQLBolt', '练习 30m', 'https://sqlbolt.com/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ostep', 'operating_systems', 'doc', 'Operating Systems: Three Easy Pieces', 'OSTEP', '长期参考', 'https://pages.cs.wisc.edu/~remzi/OSTEP/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('os-review', 'operating_systems', 'article', '进程、线程与内存管理复盘提纲', '静态推荐', '阅读 25m', 'https://pages.cs.wisc.edu/~remzi/OSTEP/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mdn-http-overview', 'computer_networks', 'doc', 'HTTP 与 Web 通信总览', 'MDN', '长期参考', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('network-learning', 'computer_networks', 'article', '网络分层与请求路径入门', 'Cloudflare', '阅读 20m', 'https://www.cloudflare.com/learning/network-layer/what-is-a-computer-network/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ml-crash-course', 'machine_learning', 'doc', 'Machine Learning Crash Course', 'Google', '长期参考', 'https://developers.google.com/machine-learning/crash-course', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ml-eval-notes', 'machine_learning', 'article', '特征工程与模型评估入门', '静态推荐', '阅读 22m', 'https://developers.google.com/machine-learning/crash-course/framing/check-your-understanding', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('nand2tetris', 'digital_logic', 'doc', 'Nand to Tetris 课程主页', 'Nand2Tetris', '长期参考', 'https://www.nand2tetris.org/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('digital-logic-video', 'digital_logic', 'video', '数字逻辑与硬件系统导学', 'Bilibili', '3h 40m', 'https://www.bilibili.com', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('computer-history-timeline', 'cs_history', 'doc', 'Computer History Timeline', 'Computer History Museum', '长期参考', 'https://www.computerhistory.org/timeline/computers/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('opensource-history', 'cs_history', 'article', '从技术史到开源协作的脉络速览', '静态推荐', '阅读 16m', 'https://opensource.com/resources/what-open-source', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('career-planning-guide', 'career_positioning', 'doc', '职业规划入门指南', 'Coursera', '长期参考', 'https://www.coursera.org/articles/career-planning', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('job-role-notes', 'career_positioning', 'article', '岗位方向拆解与自我评估清单', '静态推荐', '阅读 15m', 'https://www.indeed.com/career-advice/finding-a-job/career-planning-guide', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('resume-guide', 'resume_portfolio', 'doc', '简历写作与作品集整理指南', 'Indeed', '长期参考', 'https://www.indeed.com/career-advice/resumes-cover-letters', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('portfolio-checklist', 'resume_portfolio', 'article', '项目经历与作品集表达检查表', '静态推荐', '阅读 18m', 'https://www.indeed.com/career-advice/resumes-cover-letters/how-to-make-a-portfolio', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('interview-question-guide', 'interview_preparation', 'doc', '常见面试问题准备指南', 'Indeed', '长期参考', 'https://www.indeed.com/career-advice/interviewing/common-interview-questions-and-answers', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('behavioral-interview-notes', 'interview_preparation', 'article', 'STAR 法则与面试复盘模板', '静态推荐', '阅读 20m', 'https://www.themuse.com/advice/star-interview-method', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('workplace-communication', 'workplace_communication', 'doc', '职场沟通基础手册', 'MindTools', '长期参考', 'https://www.mindtools.com/CommSkll/CommunicationIntro.htm', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('daily-sync-template', 'workplace_communication', 'article', '日报、周报与同步进度的表达模板', '静态推荐', '阅读 12m', 'https://www.atlassian.com/blog/productivity/how-to-write-status-updates', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('stress-management-guide', 'stress_management', 'doc', '压力管理基础指南', 'Mind', '长期参考', 'https://www.mind.org.uk/information-support/types-of-mental-health-problems/stress/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('stress-reset-checklist', 'stress_management', 'article', '高压阶段的恢复动作清单', '静态推荐', '阅读 10m', 'https://www.helpguide.org/mental-health/stress/stress-management', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('growth-mindset', 'growth_mindset', 'doc', 'Growth Mindset 入门材料', 'Mindset Works', '长期参考', 'https://www.mindsetworks.com/science/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('feedback-reframe', 'growth_mindset', 'article', '如何把失败和反馈转化为下一轮行动', '静态推荐', '阅读 14m', 'https://fs.blog/carol-dweck-mindset/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('computational-thinking-course', 'computational_thinking', 'doc', 'Computational Thinking for Problem Solving', 'University of Pennsylvania', '长期参考', 'https://www.coursera.org/learn/computational-thinking-problem-solving', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('problem-decomposition-notes', 'computational_thinking', 'article', '问题抽象与任务拆解练习清单', '静态推荐', '阅读 18m', 'https://developers.google.com/tech-writing', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('system-design-primer', 'software_architecture_design', 'doc', 'System Design Primer', 'GitHub', '长期参考', 'https://github.com/donnemartin/system-design-primer', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('architecture-checklist', 'software_architecture_design', 'article', '系统分层与模块边界检查表', '静态推荐', '阅读 20m', 'https://martinfowler.com/architecture/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('etl-overview', 'data_warehouse_etl', 'doc', 'ETL 与数据仓库基础总览', 'IBM', '长期参考', 'https://www.ibm.com/topics/etl', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('analytics-metric-model', 'data_warehouse_etl', 'article', '指标口径与数仓建模入门', '静态推荐', '阅读 16m', 'https://www.getdbt.com/blog/what-is-dimensional-modeling', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('resilience-patterns', 'service_governance_resilience', 'doc', 'Resilience Patterns', 'Microsoft', '长期参考', 'https://learn.microsoft.com/en-us/azure/architecture/patterns/category/resiliency', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('governance-playbook', 'service_governance_resilience', 'article', '限流、熔断与重试策略速查', '静态推荐', '阅读 15m', 'https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('openai-prompt-guide', 'prompt_rag_agent', 'doc', 'Prompt Engineering Guide', 'Prompting Guide', '长期参考', 'https://www.promptingguide.ai/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('rag-agent-notes', 'prompt_rag_agent', 'article', 'RAG 与 Agent 方案拆解清单', '静态推荐', '阅读 22m', 'https://www.pinecone.io/learn/retrieval-augmented-generation/', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('star-storytelling', 'project_storytelling', 'doc', 'STAR 项目叙事模板', 'The Muse', '长期参考', 'https://www.themuse.com/advice/star-interview-method', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('project-presentation-checklist', 'project_storytelling', 'article', '项目成果表达与量化结果检查表', '静态推荐', '阅读 12m', 'https://www.indeed.com/career-advice/interviewing/project-based-interview-questions', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE
    node_code = VALUES(node_code),
    resource_type = VALUES(resource_type),
    title = VALUES(title),
    source_label = VALUES(source_label),
    duration_label = VALUES(duration_label),
    link_url = VALUES(link_url),
    sort_order = VALUES(sort_order),
    updated_at = CURRENT_TIMESTAMP;
