INSERT INTO skill_node_resources(
    resource_code,
    node_code,
    resource_type,
    title,
    source_label,
    duration_label,
    link_url,
    sort_order,
    created_at,
    updated_at
) VALUES
('auto_ai_codebase_grounding_ref', 'ai_codebase_grounding', 'doc', 'Model Context Protocol Introduction', 'MCP', '长期参考', 'https://modelcontextprotocol.io/introduction', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_ai_data_science_ref', 'ai_data_science', 'doc', 'Machine Learning Crash Course', 'Google', '长期参考', 'https://developers.google.com/machine-learning/crash-course', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_ai_pair_programming_ref', 'ai_pair_programming', 'doc', 'GitHub Copilot Docs', 'GitHub Docs', '长期参考', 'https://docs.github.com/en/copilot', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_algorithms_analysis_ref', 'algorithms_analysis', 'doc', 'Algorithms, 4th Edition', 'Princeton', '长期参考', 'https://algs4.cs.princeton.edu/home/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_analytics_data_visualization_ref', 'analytics_data_visualization', 'doc', 'Plotly Python Getting Started', 'Plotly', '长期参考', 'https://plotly.com/python/getting-started/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_api_contract_design_ref', 'api_contract_design', 'doc', 'Best practices for RESTful API design', 'Microsoft Learn', '长期参考', 'https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_applied_cryptography_ref', 'applied_cryptography', 'article', 'What is encryption?', 'Cloudflare', '阅读 10m', 'https://www.cloudflare.com/learning/ssl/what-is-encryption/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_automated_testing_ref', 'automated_testing', 'article', 'The Practical Test Pyramid', 'Martin Fowler', '阅读 18m', 'https://martinfowler.com/articles/practical-test-pyramid.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_big_data_foundations_ref', 'big_data_foundations', 'article', 'What is big data?', 'IBM', '阅读 10m', 'https://www.ibm.com/think/topics/big-data', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_browser_runtime_mechanics_ref', 'browser_runtime_mechanics', 'doc', 'JavaScript Event Loop', 'MDN', '长期参考', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_burnout_prevention_ref', 'burnout_prevention', 'article', 'Burnout prevention and recovery', 'HelpGuide', '阅读 10m', 'https://www.helpguide.org/mental-health/stress/burnout-prevention-and-recovery', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_c_programming_basics_ref', 'c_programming_basics', 'doc', 'C language reference', 'cppreference', '长期参考', 'https://en.cppreference.com/w/c/language.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_career_employment_readiness_ref', 'career_employment_readiness', 'article', 'What Is Career Development?', 'Coursera', '阅读 12m', 'https://www.coursera.org/articles/career-development', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_ci_cd_pipeline_ref', 'ci_cd_pipeline', 'doc', 'Understanding GitHub Actions', 'GitHub Docs', '长期参考', 'https://docs.github.com/en/actions/about-github-actions/understanding-github-actions', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_cloud_native_basics_ref', 'cloud_native_basics', 'doc', 'CNCF Cloud Native Glossary', 'CNCF', '长期参考', 'https://glossary.cncf.io/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_collaborative_development_ref', 'collaborative_development', 'doc', 'Git Tutorials', 'Atlassian', '长期参考', 'https://www.atlassian.com/git/tutorials', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_compiler_principles_ref', 'compiler_principles', 'doc', 'My First Language Frontend with LLVM', 'LLVM', '长期参考', 'https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_computer_organization_ref', 'computer_organization', 'doc', 'Nand to Tetris', 'Nand2Tetris', '长期参考', 'https://www.nand2tetris.org/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_concurrent_programming_basics_ref', 'concurrent_programming_basics', 'doc', 'Concurrency', 'Oracle', '长期参考', 'https://docs.oracle.com/javase/tutorial/essential/concurrency/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_container_kubernetes_ref', 'container_kubernetes', 'doc', 'Kubernetes Basics', 'Kubernetes', '长期参考', 'https://kubernetes.io/docs/tutorials/kubernetes-basics/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_data_cleaning_feature_engineering_ref', 'data_cleaning_feature_engineering', 'doc', 'Preprocessing data', 'scikit-learn', '长期参考', 'https://scikit-learn.org/stable/modules/preprocessing.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_data_database_systems_ref', 'data_database_systems', 'article', 'Database management', 'IBM', '阅读 12m', 'https://www.ibm.com/think/topics/database-management', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_data_modeling_ref', 'data_modeling', 'article', 'What is data modeling?', 'IBM', '阅读 10m', 'https://www.ibm.com/think/topics/data-modeling', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_data_structures_ref', 'data_structures', 'tool', 'VisuAlgo 数据结构可视化', 'VisuAlgo', '互动参考', 'https://visualgo.net/en', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_deep_learning_ref', 'deep_learning', 'doc', 'Learn the Basics', 'PyTorch', '长期参考', 'https://pytorch.org/tutorials/beginner/basics/intro.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_design_patterns_refactoring_ref', 'design_patterns_refactoring', 'doc', 'Design Patterns', 'Refactoring.Guru', '长期参考', 'https://refactoring.guru/design-patterns', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_devops_delivery_ref', 'devops_delivery', 'doc', 'What is DevOps?', 'Atlassian', '长期参考', 'https://www.atlassian.com/devops', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_discrete_mathematics_ref', 'discrete_mathematics', 'doc', 'Mathematics for Computer Science', 'MIT OCW', '长期参考', 'https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_distributed_systems_ref', 'distributed_systems', 'doc', 'MIT 6.824 Distributed Systems', 'MIT', '长期参考', 'https://pdos.csail.mit.edu/6.824/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_domain_modeling_design_ref', 'domain_modeling_design', 'article', 'Domain Model', 'Martin Fowler', '阅读 8m', 'https://martinfowler.com/eaaCatalog/domainModel.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_embedded_systems_ref', 'embedded_systems', 'doc', 'Zephyr Project Introduction', 'Zephyr', '长期参考', 'https://docs.zephyrproject.org/latest/introduction/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_emotion_regulation_ref', 'emotion_regulation', 'article', 'Emotional Intelligence Toolkit', 'HelpGuide', '阅读 12m', 'https://www.helpguide.org/mental-health/wellbeing/emotional-intelligence-toolkit', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_end_to_end_regression_ref', 'end_to_end_regression', 'doc', 'Playwright Introduction', 'Playwright', '长期参考', 'https://playwright.dev/docs/intro', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_engineering_code_conventions_ref', 'engineering_code_conventions', 'doc', 'Google Java Style Guide', 'Google', '长期参考', 'https://google.github.io/styleguide/javaguide.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_engineering_ethics_ref', 'engineering_ethics', 'doc', 'ACM Code of Ethics', 'ACM', '长期参考', 'https://www.acm.org/code-of-ethics', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_file_system_io_ref', 'file_system_io', 'doc', 'File System Intro', 'OSTEP', '长期参考', 'https://pages.cs.wisc.edu/~remzi/OSTEP/file-intro.pdf', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_frontend_component_architecture_ref', 'frontend_component_architecture', 'doc', 'Thinking in React', 'React Docs', '长期参考', 'https://react.dev/learn/thinking-in-react', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_frontend_engineering_ref', 'frontend_engineering', 'doc', 'MDN Learn Web Development', 'MDN', '长期参考', 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_graph_problem_modeling_ref', 'graph_problem_modeling', 'doc', 'Neo4j Graph Modeling', 'Neo4j', '长期参考', 'https://neo4j.com/books/neo4j-graph-modeling/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_habit_energy_management_ref', 'habit_energy_management', 'article', 'Habits Guide: How to Build Good Habits and Break Bad Ones', 'James Clear', '阅读 12m', 'https://jamesclear.com/habits', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_hardware_embedded_ref', 'hardware_embedded', 'doc', 'Arduino Documentation', 'Arduino', '长期参考', 'https://docs.arduino.cc/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_internship_goal_setting_ref', 'internship_goal_setting', 'article', 'How to Write SMART Goals', 'Atlassian', '阅读 8m', 'https://www.atlassian.com/blog/productivity/how-to-write-smart-goals', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_internship_workplace_adaptation_ref', 'internship_workplace_adaptation', 'article', 'Internship tips', 'Indeed', '阅读 10m', 'https://www.indeed.com/career-advice/starting-new-job/internship-tips', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_iot_system_design_ref', 'iot_system_design', 'article', 'What is the Internet of Things?', 'IBM', '阅读 10m', 'https://www.ibm.com/think/topics/internet-of-things', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_java_collections_io_ref', 'java_collections_io', 'doc', 'The Collections Trail', 'Oracle', '长期参考', 'https://docs.oracle.com/javase/tutorial/collections/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_java_programming_ref', 'java_programming', 'doc', 'Java Language Basics', 'Oracle', '长期参考', 'https://docs.oracle.com/javase/tutorial/java/nutsandbolts/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_job_market_research_ref', 'job_market_research', 'article', 'How to Read a Job Description', 'Indeed', '阅读 10m', 'https://www.indeed.com/career-advice/finding-a-job/how-to-read-a-job-description', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_linux_operations_ref', 'linux_operations', 'doc', 'Linux Journey', 'Linux Journey', '长期参考', 'https://linuxjourney.com/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_llm_applications_ref', 'llm_applications', 'doc', 'The Hugging Face LLM Course', 'Hugging Face', '长期参考', 'https://huggingface.co/learn/llm-course/chapter1/1', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_logic_and_proofs_ref', 'logic_and_proofs', 'doc', 'Mathematics for Computer Science Readings', 'MIT OCW', '长期参考', 'https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/pages/readings/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_memory_management_ref', 'memory_management', 'doc', 'Virtual Memory Intro', 'OSTEP', '长期参考', 'https://pages.cs.wisc.edu/~remzi/OSTEP/vm-intro.pdf', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_memory_model_pointers_ref', 'memory_model_pointers', 'doc', 'Pointers in C', 'cppreference', '长期参考', 'https://en.cppreference.com/w/c/language/pointer.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_microcomputer_principles_ref', 'microcomputer_principles', 'doc', 'Computer Organization and Architecture Tutorials', 'GeeksforGeeks', '长期参考', 'https://www.geeksforgeeks.org/computer-organization-architecture/computer-organization-and-architecture-tutorials/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_model_evaluation_validation_ref', 'model_evaluation_validation', 'doc', 'Model selection and evaluation', 'scikit-learn', '长期参考', 'https://scikit-learn.org/stable/model_selection.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_network_protocols_ref', 'network_protocols', 'doc', 'HTTP Overview', 'MDN', '长期参考', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_network_security_ref', 'network_security', 'article', 'What is network security?', 'Cloudflare', '阅读 10m', 'https://www.cloudflare.com/learning/security/what-is-network-security/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_networking_personal_brand_ref', 'networking_personal_brand', 'article', 'What Is Personal Branding?', 'Forbes Books', '阅读 8m', 'https://books.forbes.com/blog/what-is-personal-branding/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_neural_network_training_ref', 'neural_network_training', 'doc', 'Training Neural Networks', 'PyTorch', '长期参考', 'https://pytorch.org/tutorials/beginner/introyt/trainingyt.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_object_oriented_modeling_ref', 'object_oriented_modeling', 'article', 'What is object-oriented programming?', 'IBM', '阅读 12m', 'https://www.ibm.com/think/topics/object-oriented-programming', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_observability_incident_response_ref', 'observability_incident_response', 'doc', 'Site Reliability Engineering', 'Google SRE', '长期参考', 'https://sre.google/sre-book/table-of-contents/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_open_source_culture_ref', 'open_source_culture', 'article', 'How to Contribute to Open Source', 'Open Source Guides', '阅读 15m', 'https://opensource.guide/how-to-contribute/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_probability_inference_ref', 'probability_inference', 'doc', 'Seeing Theory: Basic Probability', 'Brown University', '长期参考', 'https://seeing-theory.brown.edu/basic-probability/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_problem_solving_patterns_ref', 'problem_solving_patterns', 'doc', 'cp-algorithms', 'cp-algorithms', '长期参考', 'https://cp-algorithms.com/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_process_thread_models_ref', 'process_thread_models', 'doc', 'Threads Intro', 'OSTEP', '长期参考', 'https://pages.cs.wisc.edu/~remzi/OSTEP/threads-intro.pdf', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_python_data_tools_ref', 'python_data_tools', 'doc', 'pandas Getting Started', 'pandas', '长期参考', 'https://pandas.pydata.org/docs/getting_started/index.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_query_optimization_ref', 'query_optimization', 'doc', 'EXPLAIN Output Format', 'MySQL', '长期参考', 'https://dev.mysql.com/doc/refman/8.0/en/explain.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_recommendation_systems_ref', 'recommendation_systems', 'doc', 'Microsoft Recommenders', 'GitHub', '长期参考', 'https://github.com/recommenders-team/recommenders', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_requirement_analysis_ref', 'requirement_analysis', 'article', 'Requirements management guide', 'Atlassian', '阅读 10m', 'https://www.atlassian.com/agile/project-management/requirements', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_secure_engineering_ref', 'secure_engineering', 'doc', 'OWASP Cheat Sheet Series', 'OWASP', '长期参考', 'https://cheatsheetseries.owasp.org/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_self_reflection_planning_ref', 'self_reflection_planning', 'article', 'How to Build a Growth Plan', 'Coursera', '阅读 12m', 'https://www.coursera.org/articles/build-a-growth-plan', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_service_layer_design_ref', 'service_layer_design', 'article', 'Service Layer', 'Martin Fowler', '阅读 10m', 'https://martinfowler.com/eaaCatalog/serviceLayer.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_shell_tooling_automation_ref', 'shell_tooling_automation', 'doc', 'Bash Reference Manual', 'GNU', '长期参考', 'https://www.gnu.org/software/bash/manual/bash.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_software_engineering_delivery_ref', 'software_engineering_delivery', 'doc', 'What is software development?', 'Atlassian', '长期参考', 'https://www.atlassian.com/software-development', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_sql_query_writing_ref', 'sql_query_writing', 'tool', 'SQLBolt', 'SQLBolt', '练习 30m', 'https://sqlbolt.com/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_state_data_flow_ref', 'state_data_flow', 'doc', 'Sharing State Between Components', 'React Docs', '长期参考', 'https://react.dev/learn/sharing-state-between-components', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_statistics_foundation_ref', 'statistics_foundation', 'doc', 'Seeing Theory', 'Brown University', '长期参考', 'https://seeing-theory.brown.edu/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_systems_infrastructure_ref', 'systems_infrastructure', 'doc', 'OSTEP Introduction', 'OSTEP', '长期参考', 'https://pages.cs.wisc.edu/~remzi/OSTEP/intro.pdf', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_task_execution_followup_ref', 'task_execution_followup', 'article', 'Write effective updates to projects, goals, and topics', 'Atlassian Support', '阅读 8m', 'https://support.atlassian.com/platform-experiences/docs/write-effective-updates-to-projects-goals-and-topics/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_teamwork_collaboration_ref', 'teamwork_collaboration', 'article', 'Teamwork examples', 'Atlassian', '阅读 10m', 'https://www.atlassian.com/blog/teamwork/teamwork-examples', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_technology_society_governance_ref', 'technology_society_governance', 'article', 'OECD AI Principles', 'OECD', '阅读 12m', 'https://oecd.ai/en/ai-principles', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_theory_history_ref', 'theory_history', 'doc', 'Computer History Timeline', 'Computer History Museum', '长期参考', 'https://www.computerhistory.org/timeline/computers/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_transaction_consistency_ref', 'transaction_consistency', 'doc', 'InnoDB Transaction Model', 'MySQL', '长期参考', 'https://dev.mysql.com/doc/refman/8.0/en/innodb-transaction-model.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_tree_linear_models_ref', 'tree_linear_models', 'doc', 'Supervised learning', 'scikit-learn', '长期参考', 'https://scikit-learn.org/stable/supervised_learning.html', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_unit_integration_testing_ref', 'unit_integration_testing', 'doc', 'JUnit 5 User Guide', 'JUnit', '长期参考', 'https://junit.org/junit5/docs/current/user-guide/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_web_security_ref', 'web_security', 'doc', 'OWASP Top 10', 'OWASP', '长期参考', 'https://owasp.org/www-project-top-ten/', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_wellbeing_self_management_ref', 'wellbeing_self_management', 'article', 'Mental health at work', 'WHO', '阅读 10m', 'https://www.who.int/news-room/fact-sheets/detail/mental-health-at-work', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('auto_workplace_professionalism_ref', 'workplace_professionalism', 'article', 'Guide to professionalism in the workplace', 'Indeed', '阅读 10m', 'https://www.indeed.com/career-advice/career-development/the-ultimate-guide-to-professionalism', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE
    node_code = VALUES(node_code),
    resource_type = VALUES(resource_type),
    title = VALUES(title),
    source_label = VALUES(source_label),
    duration_label = VALUES(duration_label),
    link_url = VALUES(link_url),
    sort_order = VALUES(sort_order),
    updated_at = CURRENT_TIMESTAMP;
